// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { normalizeClientOptions } from "../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import * as errors from "../../../../errors/index.js";
import type * as Agora from "../../../index.js";

export declare namespace AgentsClient {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class AgentsClient {
    protected readonly _options: AgentsClient.Options;

    constructor(options: AgentsClient.Options) {
        this._options = normalizeClientOptions(options);
    }

    /**
     * Create and start a Conversational AI agent instance.
     *
     * @param {Agora.StartAgentsRequest} request
     * @param {AgentsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.agents.start({
     *         appid: "appid",
     *         name: "unique_name",
     *         properties: {
     *             channel: "channel_name",
     *             token: "token",
     *             agent_rtc_uid: "1001",
     *             remote_rtc_uids: ["1002"],
     *             idle_timeout: 120,
     *             asr: {
     *                 vendor: "ares",
     *                 vendor: "ares"
     *             },
     *             tts: {
     *                 vendor: "microsoft",
     *                 params: {
     *                     key: "key",
     *                     region: "region",
     *                     voice_name: "voice_name"
     *                 }
     *             },
     *             llm: {
     *                 url: "https://api.openai.com/v1/chat/completions",
     *                 api_key: "<your_llm_key>",
     *                 system_messages: [{
     *                         "role": "system",
     *                         "content": "You are a helpful chatbot."
     *                     }],
     *                 params: {
     *                     model: "gpt-4o-mini"
     *                 },
     *                 max_history: 32,
     *                 greeting_message: "Hello, how can I assist you today?",
     *                 failure_message: "Please hold on a second."
     *             },
     *             turn_detection: {
     *                 mode: "default",
     *                 config: {
     *                     end_of_speech: {
     *                         mode: "semantic"
     *                     }
     *                 }
     *             }
     *         }
     *     })
     */
    public start(
        request: Agora.StartAgentsRequest,
        requestOptions?: AgentsClient.RequestOptions,
    ): core.HttpResponsePromise<Agora.StartAgentsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__start(request, requestOptions));
    }

    private async __start(
        request: Agora.StartAgentsRequest,
        requestOptions?: AgentsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Agora.StartAgentsResponse>> {
        const { appid, ..._body } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                ...(await this._getCustomAuthorizationHeaders()),
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AgoraEnvironment.Default,
                `v2/projects/${core.url.encodePathParam(appid)}/join`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Agora.StartAgentsResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.AgoraError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.AgoraError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.AgoraTimeoutError("Timeout exceeded when calling POST /v2/projects/{appid}/join.");
            case "unknown":
                throw new errors.AgoraError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Retrieve a list of agents that meet the specified conditions.
     *
     * @param {Agora.ListAgentsRequest} request
     * @param {AgentsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.agents.list({
     *         appid: "appid"
     *     })
     */
    public async list(
        request: Agora.ListAgentsRequest,
        requestOptions?: AgentsClient.RequestOptions,
    ): Promise<core.Page<Agora.ListAgentsResponse.Data.List.Item, Agora.ListAgentsResponse>> {
        const list = core.HttpResponsePromise.interceptFunction(
            async (request: Agora.ListAgentsRequest): Promise<core.WithRawResponse<Agora.ListAgentsResponse>> => {
                const { appid, channel, from_time: fromTime, to_time: toTime, state, limit, cursor } = request;
                const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
                if (channel != null) {
                    _queryParams.channel = channel;
                }
                if (fromTime != null) {
                    _queryParams.from_time = fromTime.toString();
                }
                if (toTime != null) {
                    _queryParams.to_time = toTime.toString();
                }
                if (state != null) {
                    _queryParams.state = state;
                }
                if (limit != null) {
                    _queryParams.limit = limit.toString();
                }
                if (cursor != null) {
                    _queryParams.cursor = cursor;
                }
                const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
                    this._options?.headers,
                    mergeOnlyDefinedHeaders({
                        Authorization: await this._getAuthorizationHeader(),
                        ...(await this._getCustomAuthorizationHeaders()),
                    }),
                    requestOptions?.headers,
                );
                const _response = await core.fetcher({
                    url: core.url.join(
                        (await core.Supplier.get(this._options.baseUrl)) ??
                            (await core.Supplier.get(this._options.environment)) ??
                            environments.AgoraEnvironment.Default,
                        `v2/projects/${core.url.encodePathParam(appid)}/agents`,
                    ),
                    method: "GET",
                    headers: _headers,
                    queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
                    timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
                    maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
                    abortSignal: requestOptions?.abortSignal,
                    fetchFn: this._options?.fetch,
                    logging: this._options.logging,
                });
                if (_response.ok) {
                    return { data: _response.body as Agora.ListAgentsResponse, rawResponse: _response.rawResponse };
                }
                if (_response.error.reason === "status-code") {
                    throw new errors.AgoraError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
                }
                switch (_response.error.reason) {
                    case "non-json":
                        throw new errors.AgoraError({
                            statusCode: _response.error.statusCode,
                            body: _response.error.rawBody,
                            rawResponse: _response.rawResponse,
                        });
                    case "timeout":
                        throw new errors.AgoraTimeoutError(
                            "Timeout exceeded when calling GET /v2/projects/{appid}/agents.",
                        );
                    case "unknown":
                        throw new errors.AgoraError({
                            message: _response.error.errorMessage,
                            rawResponse: _response.rawResponse,
                        });
                }
            },
        );
        const dataWithRawResponse = await list(request).withRawResponse();
        return new core.Page<Agora.ListAgentsResponse.Data.List.Item, Agora.ListAgentsResponse>({
            response: dataWithRawResponse.data,
            rawResponse: dataWithRawResponse.rawResponse,
            hasNextPage: (response) =>
                response?.meta?.cursor != null &&
                !(typeof response?.meta?.cursor === "string" && response?.meta?.cursor === ""),
            getItems: (response) => response?.data.list ?? [],
            loadPage: (response) => {
                return list(core.setObjectProperty(request, "cursor", response?.meta?.cursor));
            },
        });
    }

    /**
     * Get the current state information of the specified agent instance.
     *
     * @param {Agora.GetAgentsRequest} request
     * @param {AgentsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.agents.get({
     *         appid: "appid",
     *         agentId: "agentId"
     *     })
     */
    public get(
        request: Agora.GetAgentsRequest,
        requestOptions?: AgentsClient.RequestOptions,
    ): core.HttpResponsePromise<Agora.GetAgentsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__get(request, requestOptions));
    }

    private async __get(
        request: Agora.GetAgentsRequest,
        requestOptions?: AgentsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Agora.GetAgentsResponse>> {
        const { appid, agentId } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                ...(await this._getCustomAuthorizationHeaders()),
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AgoraEnvironment.Default,
                `v2/projects/${core.url.encodePathParam(appid)}/agents/${core.url.encodePathParam(agentId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Agora.GetAgentsResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.AgoraError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.AgoraError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.AgoraTimeoutError(
                    "Timeout exceeded when calling GET /v2/projects/{appid}/agents/{agentId}.",
                );
            case "unknown":
                throw new errors.AgoraError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Get the history of the conversation between the user and the agent.
     *
     * Call this endpoint while the agent is running to retrieve the conversation history. You can set the maximum number of cached entries using the `llm.max_history` parameter when calling the start agent endpoint. The default value is `32`.
     *
     * @param {Agora.GetHistoryAgentsRequest} request
     * @param {AgentsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.agents.getHistory({
     *         appid: "appid",
     *         agentId: "agentId"
     *     })
     */
    public getHistory(
        request: Agora.GetHistoryAgentsRequest,
        requestOptions?: AgentsClient.RequestOptions,
    ): core.HttpResponsePromise<Agora.GetHistoryAgentsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getHistory(request, requestOptions));
    }

    private async __getHistory(
        request: Agora.GetHistoryAgentsRequest,
        requestOptions?: AgentsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Agora.GetHistoryAgentsResponse>> {
        const { appid, agentId } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                ...(await this._getCustomAuthorizationHeaders()),
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AgoraEnvironment.Default,
                `v2/projects/${core.url.encodePathParam(appid)}/agents/${core.url.encodePathParam(agentId)}/history`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Agora.GetHistoryAgentsResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.AgoraError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.AgoraError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.AgoraTimeoutError(
                    "Timeout exceeded when calling GET /v2/projects/{appid}/agents/{agentId}/history.",
                );
            case "unknown":
                throw new errors.AgoraError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Query conversation turn information for a conversational AI agent session.
     *
     * After a conversation with the agent ends, use this endpoint to query the conversation turn information, including the start information, end information, and performance metrics of each conversation turn.
     *
     * You can query sessions within the last 7 days.
     *
     * @param {Agora.GetTurnsAgentsRequest} request
     * @param {AgentsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.agents.getTurns({
     *         appid: "appid",
     *         agentId: "agentId"
     *     })
     */
    public getTurns(
        request: Agora.GetTurnsAgentsRequest,
        requestOptions?: AgentsClient.RequestOptions,
    ): core.HttpResponsePromise<Agora.GetTurnsAgentsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getTurns(request, requestOptions));
    }

    private async __getTurns(
        request: Agora.GetTurnsAgentsRequest,
        requestOptions?: AgentsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Agora.GetTurnsAgentsResponse>> {
        const { appid, agentId, page_index: pageIndex, page_size: pageSize } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (pageIndex != null) {
            _queryParams.page_index = pageIndex.toString();
        }

        if (pageSize != null) {
            _queryParams.page_size = pageSize.toString();
        }

        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                ...(await this._getCustomAuthorizationHeaders()),
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AgoraEnvironment.Default,
                `v2/projects/${core.url.encodePathParam(appid)}/agents/${core.url.encodePathParam(agentId)}/turns`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Agora.GetTurnsAgentsResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.AgoraError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.AgoraError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.AgoraTimeoutError(
                    "Timeout exceeded when calling GET /v2/projects/{appid}/agents/{agentId}/turns.",
                );
            case "unknown":
                throw new errors.AgoraError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Stop the specified conversational agent instance. The API responds after request parameters are validated, and the stop operation is processed asynchronously after the response is returned.
     *
     * @param {Agora.StopAgentsRequest} request
     * @param {AgentsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.agents.stop({
     *         appid: "appid",
     *         agentId: "agentId"
     *     })
     */
    public stop(
        request: Agora.StopAgentsRequest,
        requestOptions?: AgentsClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__stop(request, requestOptions));
    }

    private async __stop(
        request: Agora.StopAgentsRequest,
        requestOptions?: AgentsClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { appid, agentId } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                ...(await this._getCustomAuthorizationHeaders()),
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AgoraEnvironment.Default,
                `v2/projects/${core.url.encodePathParam(appid)}/agents/${core.url.encodePathParam(agentId)}/leave`,
            ),
            method: "POST",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.AgoraError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.AgoraError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.AgoraTimeoutError(
                    "Timeout exceeded when calling POST /v2/projects/{appid}/agents/{agentId}/leave.",
                );
            case "unknown":
                throw new errors.AgoraError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Adjust Conversation AI Engine parameters at runtime.
     *
     * @param {Agora.UpdateAgentsRequest} request
     * @param {AgentsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.agents.update({
     *         appid: "appid",
     *         agentId: "agentId",
     *         properties: {
     *             token: "007eJxTYxxxxxxxxxxIaHMLAAAA0ex66",
     *             llm: {
     *                 system_messages: [{
     *                         "role": "system",
     *                         "content": "You are a helpful assistant. xxx"
     *                     }, {
     *                         "role": "system",
     *                         "content": "Previously, user has talked about their favorite hobbies with some key topics: xxx"
     *                     }],
     *                 params: {
     *                     "model": "abab6.5s-chat",
     *                     "max_token": 1024
     *                 }
     *             }
     *         }
     *     })
     */
    public update(
        request: Agora.UpdateAgentsRequest,
        requestOptions?: AgentsClient.RequestOptions,
    ): core.HttpResponsePromise<Agora.UpdateAgentsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__update(request, requestOptions));
    }

    private async __update(
        request: Agora.UpdateAgentsRequest,
        requestOptions?: AgentsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Agora.UpdateAgentsResponse>> {
        const { appid, agentId, ..._body } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                ...(await this._getCustomAuthorizationHeaders()),
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AgoraEnvironment.Default,
                `v2/projects/${core.url.encodePathParam(appid)}/agents/${core.url.encodePathParam(agentId)}/update`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Agora.UpdateAgentsResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.AgoraError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.AgoraError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.AgoraTimeoutError(
                    "Timeout exceeded when calling POST /v2/projects/{appid}/agents/{agentId}/update.",
                );
            case "unknown":
                throw new errors.AgoraError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Broadcast a custom message using the TTS module.
     *
     * During a conversation with an agent, call this endpoint to immediately broadcast a custom message using the TTS module. Upon receiving the request, the system interrupts the agent's speech and thought process to deliver the message. This broadcast can be interrupted by human voice.
     *
     * Note: The speak API is not supported when using `mllm` configuration.
     *
     * @param {Agora.SpeakAgentsRequest} request
     * @param {AgentsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.agents.speak({
     *         appid: "appid",
     *         agentId: "agentId",
     *         text: "Sorry, the conversation content is not compliant.",
     *         priority: "INTERRUPT",
     *         interruptable: false
     *     })
     */
    public speak(
        request: Agora.SpeakAgentsRequest,
        requestOptions?: AgentsClient.RequestOptions,
    ): core.HttpResponsePromise<Agora.SpeakAgentsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__speak(request, requestOptions));
    }

    private async __speak(
        request: Agora.SpeakAgentsRequest,
        requestOptions?: AgentsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Agora.SpeakAgentsResponse>> {
        const { appid, agentId, ..._body } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                ...(await this._getCustomAuthorizationHeaders()),
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AgoraEnvironment.Default,
                `v2/projects/${core.url.encodePathParam(appid)}/agents/${core.url.encodePathParam(agentId)}/speak`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Agora.SpeakAgentsResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.AgoraError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.AgoraError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.AgoraTimeoutError(
                    "Timeout exceeded when calling POST /v2/projects/{appid}/agents/{agentId}/speak.",
                );
            case "unknown":
                throw new errors.AgoraError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Interrupt the specified agent while speaking or thinking.
     *
     * @param {Agora.InterruptAgentsRequest} request
     * @param {AgentsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.agents.interrupt({
     *         appid: "appid",
     *         agentId: "agentId"
     *     })
     */
    public interrupt(
        request: Agora.InterruptAgentsRequest,
        requestOptions?: AgentsClient.RequestOptions,
    ): core.HttpResponsePromise<Agora.InterruptAgentsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__interrupt(request, requestOptions));
    }

    private async __interrupt(
        request: Agora.InterruptAgentsRequest,
        requestOptions?: AgentsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Agora.InterruptAgentsResponse>> {
        const { appid, agentId, ..._body } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                ...(await this._getCustomAuthorizationHeaders()),
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AgoraEnvironment.Default,
                `v2/projects/${core.url.encodePathParam(appid)}/agents/${core.url.encodePathParam(agentId)}/interrupt`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Agora.InterruptAgentsResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.AgoraError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.AgoraError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.AgoraTimeoutError(
                    "Timeout exceeded when calling POST /v2/projects/{appid}/agents/{agentId}/interrupt.",
                );
            case "unknown":
                throw new errors.AgoraError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getAuthorizationHeader(): Promise<string | undefined> {
        return core.BasicAuth.toAuthorizationHeader({
            username: await core.Supplier.get(this._options.username),
            password: await core.Supplier.get(this._options.password),
        });
    }

    protected async _getCustomAuthorizationHeaders(): Promise<Record<string, string | undefined>> {
        const authorizationValue = await core.Supplier.get(this._options.authorization);
        return { Authorization: authorizationValue };
    }
}
