// This file was auto-generated by Fern from our API Definition.

import type * as Agora from "../../../../index.js";

/**
 * @example
 *     {
 *         appid: "appid"
 *     }
 */
export interface ListAgentsRequest {
    /** The App ID of the project. */
    appid: string;
    /** The channel to query for a list of agents. */
    channel?: string;
    /** The start timestamp (in seconds) for the query. Default is 2 hours ago. */
    from_time?: number;
    /** The end timestamp (in seconds) for the query. Default is current time. */
    to_time?: number;
    /**
     * The agent state to filter by. Only one state can be specified per query:
     * - `IDLE` (0): Agent is idle.
     * - `STARTING` (1): The agent is being started.
     * - `RUNNING` (2): The agent is running.
     * - `STOPPING` (3): The agent is stopping.
     * - `STOPPED` (4): The agent has exited.
     * - `FAILED` (6): The agent failed to execute.
     */
    state?: Agora.ListAgentsRequestState;
    /** The maximum number of entries returned per page. */
    limit?: number;
    /** The paging cursor, indicating the starting position (`agent_id`) of the next page of results. */
    cursor?: string;
}
