// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { normalizeClientOptions } from "../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import * as errors from "../../../../errors/index.js";
import type * as Agora from "../../../index.js";

export declare namespace AgentManagementClient {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * Operations for managing conversational AI agents
 */
export class AgentManagementClient {
    protected readonly _options: AgentManagementClient.Options;

    constructor(options: AgentManagementClient.Options) {
        this._options = normalizeClientOptions(options);
    }

    /**
     * Send a custom text instruction to the specified conversational AI agent instance.
     *
     * The instruction is injected into the current conversation pipeline as user input, and the agent processes and responds to it following the standard user input logic.
     *
     * Use this endpoint for the following scenarios:
     * - **Implicit instruction injection**: Inject hidden context or directives into the conversation.
     * - **Client-side event triggering**: Notify the agent of client-side events, such as a user clicking a button.
     * - **Voice and text collaboration**: Combine text instructions with voice input for richer interaction.
     *
     * @param {Agora.AgentThinkRequest} request
     * @param {AgentManagementClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.agentManagement.agentThink({
     *         appid: "appid",
     *         agentId: "agentId",
     *         text: "The user just clicked the purchase button.",
     *         on_listening_action: "inject",
     *         on_thinking_action: "interrupt",
     *         on_speaking_action: "ignore",
     *         interruptable: true,
     *         metadata: {
     *             "publisher": "user123",
     *             "model": "deepseek-r1"
     *         }
     *     })
     */
    public agentThink(
        request: Agora.AgentThinkRequest,
        requestOptions?: AgentManagementClient.RequestOptions,
    ): core.HttpResponsePromise<Agora.AgentThinkResponse> {
        return core.HttpResponsePromise.fromPromise(this.__agentThink(request, requestOptions));
    }

    private async __agentThink(
        request: Agora.AgentThinkRequest,
        requestOptions?: AgentManagementClient.RequestOptions,
    ): Promise<core.WithRawResponse<Agora.AgentThinkResponse>> {
        const { appid, agentId, ..._body } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                ...(await this._getCustomAuthorizationHeaders()),
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AgoraEnvironment.Default,
                `v2/projects/${core.url.encodePathParam(appid)}/agents/${core.url.encodePathParam(agentId)}/think`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Agora.AgentThinkResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.AgoraError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.AgoraError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.AgoraTimeoutError(
                    "Timeout exceeded when calling POST /v2/projects/{appid}/agents/{agentId}/think.",
                );
            case "unknown":
                throw new errors.AgoraError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getAuthorizationHeader(): Promise<string | undefined> {
        return core.BasicAuth.toAuthorizationHeader({
            username: await core.Supplier.get(this._options.username),
            password: await core.Supplier.get(this._options.password),
        });
    }

    protected async _getCustomAuthorizationHeaders(): Promise<Record<string, string | undefined>> {
        const authorizationValue = await core.Supplier.get(this._options.authorization);
        return { Authorization: authorizationValue };
    }
}
