// This file was auto-generated by Fern from our API Definition.

/**
 * Error response returned when a Conversational AI Agent Management API request fails.
 *
 * Common HTTP status codes include:
 * - `400`: Invalid request parameters.
 * - `401`: Authentication failed.
 * - `403`: Unauthorized access or service not enabled.
 * - `404`: Agent not found or has exited.
 * - `409`: Agent conflict.
 * - `422`: Access limit exceeded.
 * - `429`: Request rate limit exceeded.
 * - `500`: Internal server error.
 * - `502`: Gateway error.
 * - `503`: Agent startup failure.
 * - `504`: Request timeout.
 */
export interface AgentErrorResponse {
    /** Error detail message. */
    detail?: string;
    /** Error reason code. */
    reason?: AgentErrorResponse.Reason;
}

export namespace AgentErrorResponse {
    /** Error reason code. */
    export const Reason = {
        ServiceNotEnabled: "ServiceNotEnabled",
        AccountSuspended: "AccountSuspended",
        InternalError: "InternalError",
        InvalidPermission: "InvalidPermission",
        InvalidRequestBody: "InvalidRequestBody",
        MissingRequiredField: "MissingRequiredField",
        InvalidFieldValue: "InvalidFieldValue",
        ResourceQuotaLimitExceeded: "ResourceQuotaLimitExceeded",
        ConcurrencyLimitExceeded: "ConcurrencyLimitExceeded",
        ServiceUnavailable: "ServiceUnavailable",
        ResourceAllocationFailed: "ResourceAllocationFailed",
        TaskConflict: "TaskConflict",
        TaskNotFound: "TaskNotFound",
        TaskOperationTimeout: "TaskOperationTimeout",
        NotImplemented: "NotImplemented",
    } as const;
    export type Reason = (typeof Reason)[keyof typeof Reason];
}
