// This file was auto-generated by Fern from our API Definition.

import type * as Agora from "../index.js";

/**
 * Amazon Transcribe ASR configuration.
 */
export interface AmazonAsr {
    language?: Agora.AsrLanguage;
    params: Agora.AmazonAsrParams;
    /** Accepts any additional properties */
    [key: string]: any;
}
