// This file was auto-generated by Fern from our API Definition.

/**
 * Amazon Transcribe ASR configuration parameters.
 */
export interface AmazonAsrParams {
    /** AWS region */
    region: string;
    /** AWS access key ID */
    access_key_id: string;
    /** AWS secret access key */
    secret_access_key: string;
    /** Language code for speech recognition */
    language_code: string;
    /** Sample rate in Hertz for the audio input */
    media_sample_rate_hz?: number | null;
    /** Encoding format of the audio input */
    media_encoding?: string | null;
    /** Accepts any additional properties */
    [key: string]: any;
}
