// This file was auto-generated by Fern from our API Definition.

import type * as Agora from "../index.js";

/**
 * Adaptive Recognition Engine for Speech ASR configuration.
 */
export interface AresAsr {
    language?: Agora.AsrLanguage;
    params?: Agora.AresAsrParams;
    /** Accepts any additional properties */
    [key: string]: any;
}
