// This file was auto-generated by Fern from our API Definition.

import type * as Agora from "../index.js";

export type Asr =
    | Agora.Asr.Ares
    | Agora.Asr.Microsoft
    | Agora.Asr.Deepgram
    | Agora.Asr.Openai
    | Agora.Asr.Google
    | Agora.Asr.Amazon
    | Agora.Asr.Assemblyai
    | Agora.Asr.Speechmatics
    | Agora.Asr.Sarvam
    | Asr.Fengming
    | Asr.Tencent
    | Asr.Xfyun
    | Asr.XfyunBigmodel
    | Asr.XfyunDialect;

export namespace Asr {
    export interface Ares extends Agora.AresAsr {
        vendor: "ares";
    }

    export interface Microsoft extends Agora.MicrosoftAsr {
        vendor: "microsoft";
    }

    export interface Deepgram extends Agora.DeepgramAsr {
        vendor: "deepgram";
    }

    export interface Openai extends Agora.OpenAiAsr {
        vendor: "openai";
    }

    export interface Google extends Agora.GoogleAsr {
        vendor: "google";
    }

    export interface Amazon extends Agora.AmazonAsr {
        vendor: "amazon";
    }

    export interface Assemblyai extends Agora.AssemblyAiAsr {
        vendor: "assemblyai";
    }

    export interface Speechmatics extends Agora.SpeechmaticsAsr {
        vendor: "speechmatics";
    }

    export interface Sarvam extends Agora.SarvamAsr {
        vendor: "sarvam";
    }

    export interface Fengming {
        vendor: "fengming";
        language?: string;
        params?: Record<string, unknown>;
    }

    export interface Tencent {
        vendor: "tencent";
        language?: string;
        params?: Record<string, unknown>;
    }

    export interface Xfyun {
        vendor: "xfyun";
        language?: string;
        params?: Record<string, unknown>;
    }

    export interface XfyunBigmodel {
        vendor: "xfyun_bigmodel";
        language?: string;
        params?: Record<string, unknown>;
    }

    export interface XfyunDialect {
        vendor: "xfyun_dialect";
        language?: string;
        params?: Record<string, unknown>;
    }
}
