// This file was auto-generated by Fern from our API Definition.

import type * as Agora from "../index.js";

export type Asr =
    | Agora.Asr.Ares
    | Agora.Asr.Fengming
    | Agora.Asr.Tencent
    | Agora.Asr.Microsoft
    | Agora.Asr.Deepgram
    | Agora.Asr.Openai
    | Agora.Asr.Google
    | Agora.Asr.Amazon
    | Agora.Asr.Assemblyai
    | Agora.Asr.Speechmatics
    | Agora.Asr.Sarvam
    | Agora.Asr.Xai
    | Agora.Asr.Xfyun
    | Agora.Asr.XfyunBigmodel
    | Agora.Asr.XfyunDialect;

export namespace Asr {
    export interface Ares extends Agora.AresAsr {
        vendor: "ares";
    }

    export interface Fengming extends Agora.FengmingAsr {
        vendor: "fengming";
    }

    export interface Tencent extends Agora.TencentAsr {
        vendor: "tencent";
    }

    export interface Microsoft extends Agora.MicrosoftAsr {
        vendor: "microsoft";
    }

    export interface Deepgram extends Agora.DeepgramAsr {
        vendor: "deepgram";
    }

    export interface Openai extends Agora.OpenAiAsr {
        vendor: "openai";
    }

    export interface Google extends Agora.GoogleAsr {
        vendor: "google";
    }

    export interface Amazon extends Agora.AmazonAsr {
        vendor: "amazon";
    }

    export interface Assemblyai extends Agora.AssemblyAiAsr {
        vendor: "assemblyai";
    }

    export interface Speechmatics extends Agora.SpeechmaticsAsr {
        vendor: "speechmatics";
    }

    export interface Sarvam extends Agora.SarvamAsr {
        vendor: "sarvam";
    }

    export interface Xai extends Agora.XAiAsr {
        vendor: "xai";
    }

    export interface Xfyun extends Agora.XfyunAsr {
        vendor: "xfyun";
    }

    export interface XfyunBigmodel extends Agora.XfyunBigmodelAsr {
        vendor: "xfyun_bigmodel";
    }

    export interface XfyunDialect extends Agora.XfyunDialectAsr {
        vendor: "xfyun_dialect";
    }
}
