// This file was auto-generated by Fern from our API Definition.

/**
 * AssemblyAI ASR configuration parameters.
 */
export interface AssemblyAiAsrParams {
    /** AssemblyAI API key */
    api_key: string;
    /** Language code for speech recognition */
    language: string;
    /** WebSocket URL for AssemblyAI's streaming API */
    uri?: string | null;
    /** Accepts any additional properties */
    [key: string]: any;
}
