// This file was auto-generated by Fern from our API Definition.

import type * as Agora from "../index.js";

/**
 * AssemblyAI ASR configuration.
 */
export interface AssemblyAiAsr {
    language?: Agora.AsrLanguage;
    params: Agora.AssemblyAiAsrParams;
    /** Accepts any additional properties */
    [key: string]: any;
}
