// This file was auto-generated by Fern from our API Definition.

import type * as Agora from "../index.js";

/**
 * Bytedance duplex streaming Text-to-Speech configuration.
 */
export interface BytedanceDuplexTts {
    params: Agora.BytedanceDuplexTtsParams;
    /** Controls whether the TTS module skips bracketed content when reading LLM response text. */
    skip_patterns?: number[];
}
