// This file was auto-generated by Fern from our API Definition.

import type * as Agora from "../index.js";

/**
 * Bytedance Volcano Engine Text-to-Speech configuration.
 */
export interface BytedanceTts {
    params: Agora.BytedanceTtsParams;
    /** Controls whether the TTS module skips bracketed content when reading LLM response text. */
    skip_patterns?: number[];
}
