// This file was auto-generated by Fern from our API Definition.

/**
 * Bytedance duplex streaming TTS configuration parameters.
 */
export interface BytedanceDuplexTtsParams {
    /** Bytedance application ID. */
    app_id: string;
    /** Bytedance API token. */
    token: string;
    /** Duplex TTS speaker identifier. */
    speaker: string;
    /** Accepts any additional properties */
    [key: string]: any;
}
