// This file was auto-generated by Fern from our API Definition.

/**
 * Bytedance Volcano Engine TTS configuration parameters.
 */
export interface BytedanceTtsParams {
    /** Bytedance API token. */
    token: string;
    /** Bytedance application ID. */
    app_id: string;
    /** Bytedance cluster name. */
    cluster: string;
    /** Bytedance voice type. */
    voice_type: string;
    /** Speech speed ratio. */
    speed_ratio?: number;
    /** Volume ratio. */
    volume_ratio?: number;
    /** Pitch ratio. */
    pitch_ratio?: number;
    /** Emotion preset. */
    emotion?: string;
    /** Accepts any additional properties */
    [key: string]: any;
}
