// This file was auto-generated by Fern from our API Definition.

/**
 * Cartesia voice selection.
 */
export interface CartesiaTtsVoice {
    /** Cartesia voice selection mode. */
    mode: "id";
    /** Cartesia voice ID */
    id: string;
}
