// This file was auto-generated by Fern from our API Definition.

import type * as Agora from "../index.js";

/**
 * Cartesia TTS configuration parameters.
 */
export interface CartesiaTtsParams {
    /** Cartesia API key */
    api_key: string;
    /** Model ID (for example, sonic-2) */
    model_id: string;
    /** WebSocket URL for the Cartesia streaming API */
    base_url?: string;
    voice: Agora.CartesiaTtsVoice;
    output_format?: Agora.CartesiaTtsOutputFormat;
    /** Target language for speech synthesis */
    language?: string;
    /** Accepts any additional properties */
    [key: string]: any;
}
