// This file was auto-generated by Fern from our API Definition.

import type * as Agora from "../index.js";

/**
 * Cartesia TTS configuration parameters.
 */
export interface CartesiaTtsParams {
    /** Cartesia API key */
    api_key: string;
    voice: Agora.CartesiaTtsVoice;
    /** Model ID (optional) */
    model_id?: string;
    /** Audio sampling rate in Hz */
    sample_rate?: number;
}
