// This file was auto-generated by Fern from our API Definition.

/**
 * Cartesia audio output format configuration.
 */
export interface CartesiaTtsOutputFormat {
    /** Audio container format for the output stream */
    container?: string;
    /** Audio sampling rate in Hz */
    sample_rate?: number;
    /** Accepts any additional properties */
    [key: string]: any;
}
