// This file was auto-generated by Fern from our API Definition.

/**
 * CosyVoice TTS configuration parameters.
 */
export interface CosyvoiceTtsParams {
    /** CosyVoice API key. */
    api_key: string;
    /** CosyVoice model identifier. */
    model: string;
    /** Audio sample rate in Hz. */
    sample_rate: number;
    /** CosyVoice speaker voice. */
    voice: string;
    /** Accepts any additional properties */
    [key: string]: any;
}
