// This file was auto-generated by Fern from our API Definition.

import type * as Agora from "../index.js";

/**
 * Deepgram Text-to-Speech configuration (Beta).
 */
export interface DeepgramTts {
    params: Agora.DeepgramTtsParams;
    /** Controls whether the TTS module skips bracketed content when reading LLM response text. */
    skip_patterns?: number[];
}
