// This file was auto-generated by Fern from our API Definition.

/**
 * Deepgram ASR configuration parameters.
 */
export interface DeepgramAsrParams {
    /** WebSocket URL for Deepgram's streaming API */
    url?: string | null;
    /** Deepgram API key */
    key: string;
    /** Speech recognition model */
    model?: string | null;
    /** Language code for speech recognition */
    language?: string | null;
    /** Boost specialized terms and brands for Deepgram. */
    keyterm?: string | null;
    /** Accepts any additional properties */
    [key: string]: any;
}
