// This file was auto-generated by Fern from our API Definition.

import type * as Agora from "../index.js";

/**
 * Deepgram ASR configuration.
 */
export interface DeepgramAsr {
    language?: Agora.AsrLanguage;
    params: Agora.DeepgramAsrParams;
    /** Accepts any additional properties */
    [key: string]: any;
}
