// This file was auto-generated by Fern from our API Definition.

/**
 * Deepgram TTS configuration parameters.
 */
export interface DeepgramTtsParams {
    /** Deepgram API key */
    api_key: string;
    /** Deepgram TTS model (for example, "aura-2-thalia-en") */
    model: string;
    /** Deepgram WebSocket endpoint override */
    base_url?: string;
    /** Audio sampling rate in Hz */
    sample_rate?: number;
    /** Additional Deepgram TTS parameters */
    params?: Record<string, unknown>;
    /** Controls whether the TTS module skips bracketed content when reading LLM response text. */
    skip_patterns?: number[];
}
