// This file was auto-generated by Fern from our API Definition.

/**
 * ElevenLabs TTS configuration parameters.
 */
export interface ElevenLabsTtsParams {
    /** WebSocket URL (e.g., "wss://api.elevenlabs.io/v1") */
    base_url?: string;
    /** ElevenLabs API key */
    key: string;
    /** Model ID (e.g., "eleven_flash_v2_5") */
    model_id: string;
    /** Voice ID (e.g., "pNInz6obpgDQGcFmaJgB") */
    voice_id: string;
    /** Audio sample rate in Hz (16kHz for Akool, 24kHz for HeyGen) */
    sample_rate?: number;
    /** Speech speed multiplier. */
    speed?: number;
    /** Voice stability. Higher values produce more consistent speech. */
    stability?: number;
    /** Similarity boost for the selected voice. */
    similarity_boost?: number;
    /** Speaking style and expressiveness control. */
    style?: number;
    /** Whether to improve voice quality and similarity. */
    use_speaker_boost?: boolean;
    /** Accepts any additional properties */
    [key: string]: any;
}
