// This file was auto-generated by Fern from our API Definition.

import type * as Agora from "../index.js";

/**
 * Agora Fengming ASR configuration.
 */
export interface FengmingAsr {
    language?: Agora.AsrLanguage;
    /** Agora Fengming ASR configuration parameters. */
    params?: Record<string, unknown>;
    /** Accepts any additional properties */
    [key: string]: any;
}
