// This file was auto-generated by Fern from our API Definition.

/**
 * Fish Audio TTS configuration parameters.
 */
export interface FishAudioTtsParams {
    /** Fish Audio API key */
    api_key: string;
    /** Fish Audio reference ID */
    reference_id: string;
    /** Backend model version to use */
    backend?: string;
    /** Accepts any additional properties */
    [key: string]: any;
}
