// This file was auto-generated by Fern from our API Definition.

/**
 * Generic TTS configuration parameters.
 */
export interface GenericHttpTtsParams {
    /** API key for the generic TTS service. */
    api_key?: string;
    /** TTS model name. */
    model?: string;
    /** Voice name. */
    voice?: string;
    /** Speech rate. */
    speed?: number;
    /** Output audio sample rate in Hz. */
    sample_rate?: number;
    /** Output audio format. ConvoAI currently supports `pcm` only. */
    response_format?: "pcm";
    /** Additional voice style control instruction. */
    instruction?: string;
    /** Accepts any additional properties */
    [key: string]: any;
}
