// This file was auto-generated by Fern from our API Definition.

/**
 * Google voice selection parameters.
 */
export interface GoogleTtsVoiceSelectionParams {
    /** Google voice name */
    name: string;
    /** Accepts any additional properties */
    [key: string]: any;
}
