// This file was auto-generated by Fern from our API Definition.

import type * as Agora from "../index.js";

/**
 * Google TTS configuration parameters.
 */
export interface GoogleTtsParams {
    /** Google Cloud service account credentials JSON string */
    credentials: string;
    VoiceSelectionParams: Agora.GoogleTtsVoiceSelectionParams;
    AudioConfig?: Agora.GoogleTtsAudioConfig;
    /** Accepts any additional properties */
    [key: string]: any;
}
