// This file was auto-generated by Fern from our API Definition.

/**
 * Google ASR configuration parameters.
 */
export interface GoogleAsrParams {
    /** Google Cloud project ID */
    project_id: string;
    /** Google Cloud region for the speech service */
    location: string;
    /** Google Cloud service account credentials JSON string */
    adc_credentials_string: string;
    /** Language code for speech recognition */
    language: string;
    /** Recognition model to use */
    model?: string | null;
    /** Accepts any additional properties */
    [key: string]: any;
}
