// This file was auto-generated by Fern from our API Definition.

/**
 * Google audio output configuration.
 */
export interface GoogleTtsAudioConfig {
    /** Speed of speech */
    speaking_rate?: number;
    /** Sample rate in Hz */
    sample_rate_hertz?: number;
    /** Accepts any additional properties */
    [key: string]: any;
}
