// This file was auto-generated by Fern from our API Definition.

import type * as Agora from "../index.js";

/**
 * Google ASR configuration.
 */
export interface GoogleAsr {
    language?: Agora.AsrLanguage;
    params: Agora.GoogleAsrParams;
    /** Accepts any additional properties */
    [key: string]: any;
}
