// This file was auto-generated by Fern from our API Definition.

/**
 * Gradium TTS configuration parameters.
 */
export interface GradiumTtsParams {
    /** Gradium API key. */
    api_key: string;
    /** WebSocket endpoint for streaming TTS output (for example, "wss://api.gradium.ai/api/speech/tts"). */
    url?: string;
    /** Gradium TTS model name (for example, "default"). */
    model_name?: string;
    /** Gradium voice identifier. */
    voice_id?: string;
    /** Audio sample rate in Hz (for example, 16000). */
    sample_rate?: number;
    /** Accepts any additional properties */
    [key: string]: any;
}
