// This file was auto-generated by Fern from our API Definition.

/**
 * Hume AI TTS configuration parameters.
 */
export interface HumeAiTtsParams {
    /** Hume AI API key */
    key: string;
    /** Hume AI voice ID */
    voice_id: string;
    /** Base URL for the Hume AI API */
    base_url?: string;
    /** Voice provider type */
    provider: HumeAiTtsParams.Provider;
    /** Playback speed of the generated speech */
    speed?: number;
    /** Duration of silence in seconds to add at the end of each utterance */
    trailing_silence?: number;
    /** Hume AI configuration ID. Deprecated; use voice_id for the documented TTS shape. */
    config_id?: string;
    /** Accepts any additional properties */
    [key: string]: any;
}

export namespace HumeAiTtsParams {
    /** Voice provider type */
    export const Provider = {
        HumeAi: "HUME_AI",
        CustomVoice: "CUSTOM_VOICE",
    } as const;
    export type Provider = (typeof Provider)[keyof typeof Provider];
}
