// This file was auto-generated by Fern from our API Definition.

import type * as Agora from "../index.js";

/**
 * Large language model (LLM) configuration.
 */
export interface Llm {
    /** The LLM callback address. */
    url?: string;
    /** The LLM verification API key. */
    api_key?: string;
    /** AWS access key ID. Used by Amazon Bedrock when api_key is not provided. */
    access_key?: string | null;
    /** AWS secret access key. Used by Amazon Bedrock when api_key is not provided. */
    secret_key?: string | null;
    /** AWS region. Used by Amazon Bedrock. */
    region?: string;
    /** Top-level model identifier. Used by Amazon Bedrock. */
    model?: string;
    /** A set of predefined information used as input to the LLM. */
    system_messages?: Record<string, unknown>[] | null;
    params?: Agora.LlmParams;
    /** The number of conversation history messages cached in the custom LLM. */
    max_history?: number;
    /** LLM input modalities. */
    input_modalities?: string[];
    /** LLM output modalities. */
    output_modalities?: string[];
    /** Agent greeting. */
    greeting_message?: string;
    /** Prompt for agent activation failure. */
    failure_message?: string;
    /** LLM provider identifier. */
    vendor?: string;
    /** The request style for chat completion. */
    style?: Llm.Style;
    /** Whether to handle empty Gemini responses. */
    ignore_empty?: boolean | null;
    /** Agent greeting broadcast configuration. */
    greeting_configs?: Record<string, unknown>;
    /** Template parameter configuration. */
    template_variables?: Record<string, string>;
    /** MCP server configuration. */
    mcp_servers?: Record<string, unknown>[];
    /** Custom headers to include in requests to the LLM. */
    headers?: Record<string, string>;
    /** Accepts any additional properties */
    [key: string]: any;
}

export namespace Llm {
    /** The request style for chat completion. */
    export const Style = {
        Openai: "openai",
        Gemini: "gemini",
        Anthropic: "anthropic",
        Dify: "dify",
        Bedrock: "bedrock",
    } as const;
    export type Style = (typeof Style)[keyof typeof Style];
}
