// This file was auto-generated by Fern from our API Definition.

/**
 * Additional LLM configuration parameters.
 */
export interface LlmParams {
    /** The LLM model identifier. */
    model?: string;
    /** Maximum tokens in the response. */
    max_tokens?: number;
    /** Accepts any additional properties */
    [key: string]: any;
}
