// This file was auto-generated by Fern from our API Definition.

/**
 * Microsoft Azure TTS configuration parameters.
 */
export interface MicrosoftTtsParams {
    /** Microsoft Azure API key */
    key: string;
    /** Azure region (e.g., "eastus") */
    region: string;
    /** Voice name (e.g., "en-US-AndrewMultilingualNeural") */
    voice_name: string;
    /** Audio sampling rate in Hz */
    sample_rate?: number;
    /** Speaking rate multiplier. Values between 0.5 and 2.0. */
    speed?: number;
    /** Audio volume. Values between 0.0 and 100.0. */
    volume?: number;
    /** Accepts any additional properties */
    [key: string]: any;
}
