// This file was auto-generated by Fern from our API Definition.

import type * as Agora from "../index.js";

/**
 * Microsoft Azure ASR configuration.
 */
export interface MicrosoftAsr {
    language?: Agora.AsrLanguage;
    params: Agora.MicrosoftAsrParams;
    /** Accepts any additional properties */
    [key: string]: any;
}
