// This file was auto-generated by Fern from our API Definition.

/**
 * Microsoft Azure ASR configuration parameters.
 */
export interface MicrosoftAsrParams {
    /** Microsoft Azure API key */
    key: string;
    /** Azure region */
    region: string;
    /** Language code for speech recognition */
    language: string;
    /** Words or phrases to improve recognition accuracy */
    phrase_list?: string[] | null;
    /** Accepts any additional properties */
    [key: string]: any;
}
