// This file was auto-generated by Fern from our API Definition.

/**
 * MiniMax TTS configuration parameters.
 */
export interface MinimaxTtsParams {
    /** MiniMax API key */
    key: string;
    /** MiniMax group identifier */
    group_id: string;
    /** TTS model (e.g., speech-02-turbo) */
    model: string;
    voice_setting: MinimaxTtsParams.VoiceSetting;
    /** WebSocket endpoint (e.g., wss://api-uw.minimax.io/ws/v1/t2a_v2) */
    url: string;
    /** Accepts any additional properties */
    [key: string]: any;
}

export namespace MinimaxTtsParams {
    export interface VoiceSetting {
        /** Voice style identifier (e.g., English_captivating_female1) */
        voice_id: string;
        /** Accepts any additional properties */
        [key: string]: any;
    }
}
