// This file was auto-generated by Fern from our API Definition.

/**
 * Mistral TTS configuration parameters.
 */
export interface MistralTtsParams {
    /** Mistral API key. */
    api_key: string;
    /** Mistral TTS model name (for example, "voxtral-mini-tts-2603"). */
    model?: string;
    /** Mistral voice identifier. */
    voice?: string;
    /** Accepts any additional properties */
    [key: string]: any;
}
