// This file was auto-generated by Fern from our API Definition.

import type * as Agora from "../index.js";

/**
 * Multimodal Large Language Model (MLLM) configuration for real-time audio and text processing.
 */
export interface Mllm {
    /** Enable Multimodal Large Language Model. */
    enable?: boolean | null;
    /** The MLLM WebSocket URL for real-time communication. */
    url?: string;
    /** The API key used for MLLM authentication. */
    api_key?: string;
    /** Base64-encoded Google Cloud Application Default Credentials. Used by Vertex AI. */
    adc_credentials_string?: string;
    /** Google Cloud project ID. Used by Vertex AI. */
    project_id?: string;
    /** Google Cloud location or region. Used by Vertex AI. */
    location?: string;
    /** Array of conversation items used for short-term memory management. */
    messages?: Record<string, unknown>[] | null;
    params?: Agora.MllmParams;
    /** MLLM input modalities. */
    input_modalities?: string[] | null;
    /** MLLM output modalities. */
    output_modalities?: string[] | null;
    /** Agent greeting message. */
    greeting_message?: string;
    /** Agent failure message. */
    failure_message?: string;
    /** MLLM provider. */
    vendor?: Mllm.Vendor;
    turn_detection?: Agora.MllmTurnDetection | null;
    /** Accepts any additional properties */
    [key: string]: any;
}

export namespace Mllm {
    /** MLLM provider. */
    export const Vendor = {
        Openai: "openai",
        Gemini: "gemini",
        Vertexai: "vertexai",
        Xai: "xai",
    } as const;
    export type Vendor = (typeof Vendor)[keyof typeof Vendor];
}
