// This file was auto-generated by Fern from our API Definition.

/**
 * HTTP request options for the MLLM provider.
 */
export interface MllmHttpOptions {
    /** API version to use. */
    api_version?: string | null;
    /** Accepts any additional properties */
    [key: string]: any;
}
