// This file was auto-generated by Fern from our API Definition.

/**
 * Configuration for audio input transcription.
 */
export interface MllmInputAudioTranscription {
    /** Language of the input audio. */
    language?: string | null;
    /** Model to use for transcription. */
    model?: string | null;
    /** Text to guide the transcription model. */
    prompt?: string | null;
    /** Accepts any additional properties */
    [key: string]: any;
}
