// This file was auto-generated by Fern from our API Definition.

/**
 * Turn detection configuration for the MLLM module.
 */
export interface MllmTurnDetection {
    /** Turn detection mode for MLLM. */
    mode?: MllmTurnDetection.Mode | null;
    agora_vad_config?: MllmTurnDetection.AgoraVadConfig | null;
    server_vad_config?: MllmTurnDetection.ServerVadConfig | null;
    semantic_vad_config?: MllmTurnDetection.SemanticVadConfig | null;
    /** Accepts any additional properties */
    [key: string]: any;
}

export namespace MllmTurnDetection {
    /** Turn detection mode for MLLM. */
    export const Mode = {
        AgoraVad: "agora_vad",
        ServerVad: "server_vad",
        SemanticVad: "semantic_vad",
    } as const;
    export type Mode = (typeof Mode)[keyof typeof Mode];

    export interface AgoraVadConfig {
        interrupt_duration_ms?: number | null;
        prefix_padding_ms?: number | null;
        silence_duration_ms?: number | null;
        threshold?: number | null;
        /** Accepts any additional properties */
        [key: string]: any;
    }

    export interface ServerVadConfig {
        prefix_padding_ms?: number | null;
        silence_duration_ms?: number | null;
        threshold?: number | null;
        idle_timeout_ms?: number | null;
        start_of_speech_sensitivity?: ServerVadConfig.StartOfSpeechSensitivity | null;
        end_of_speech_sensitivity?: ServerVadConfig.EndOfSpeechSensitivity | null;
        /** Accepts any additional properties */
        [key: string]: any;
    }

    export namespace ServerVadConfig {
        export const StartOfSpeechSensitivity = {
            StartSensitivityHigh: "START_SENSITIVITY_HIGH",
            StartSensitivityLow: "START_SENSITIVITY_LOW",
        } as const;
        export type StartOfSpeechSensitivity = (typeof StartOfSpeechSensitivity)[keyof typeof StartOfSpeechSensitivity];
        export const EndOfSpeechSensitivity = {
            EndSensitivityHigh: "END_SENSITIVITY_HIGH",
            EndSensitivityLow: "END_SENSITIVITY_LOW",
        } as const;
        export type EndOfSpeechSensitivity = (typeof EndOfSpeechSensitivity)[keyof typeof EndOfSpeechSensitivity];
    }

    export interface SemanticVadConfig {
        eagerness?: SemanticVadConfig.Eagerness | null;
        /** Accepts any additional properties */
        [key: string]: any;
    }

    export namespace SemanticVadConfig {
        export const Eagerness = {
            Auto: "auto",
            Low: "low",
            Medium: "medium",
            High: "high",
        } as const;
        export type Eagerness = (typeof Eagerness)[keyof typeof Eagerness];
    }
}
