// This file was auto-generated by Fern from our API Definition.

import type * as Agora from "../index.js";

/**
 * Additional MLLM configuration parameters.
 */
export interface MllmParams {
    /** The MLLM model identifier. */
    model?: string | null;
    /** Voice identifier for audio output. */
    voice?: string | null;
    /** System instructions that define the agent behavior or tone. */
    instructions?: string | null;
    input_audio_transcription?: Agora.MllmInputAudioTranscription | null;
    /** Whether to enable Gemini affective dialog. */
    affective_dialog?: boolean | null;
    /** Whether Gemini may choose not to respond when no reply is needed. */
    proactive_audio?: boolean | null;
    /** Whether to transcribe the agent speech in real time. */
    transcribe_agent?: boolean | null;
    /** Whether to transcribe the user speech in real time. */
    transcribe_user?: boolean | null;
    http_options?: Agora.MllmHttpOptions | null;
    /** Language code for xAI Grok speech recognition and synthesis. */
    language?: string | null;
    /** Audio sample rate in Hz. */
    sample_rate?: number | null;
    /** Accepts any additional properties */
    [key: string]: any;
}
