// This file was auto-generated by Fern from our API Definition.

/**
 * Murf TTS configuration parameters.
 */
export interface MurfTtsParams {
    /** Murf API key */
    api_key: string;
    /** WebSocket endpoint for streaming TTS output */
    base_url: string;
    /** Voice ID (e.g., Matthew) */
    voiceId: string;
    /** Locale for the selected voice */
    locale?: string;
    /** Speech rate adjustment */
    rate?: number;
    /** Pitch adjustment */
    pitch?: number;
    /** TTS model to use */
    model?: string;
    /** Audio sample rate in Hz */
    sample_rate?: number;
    /** Accepts any additional properties */
    [key: string]: any;
}
