// This file was auto-generated by Fern from our API Definition.

/**
 * OpenAI TTS configuration parameters.
 */
export interface OpenAiTtsParams {
    /** OpenAI API key. Optional for Agora-managed OpenAI TTS usage. */
    api_key?: string;
    /** Voice name (e.g., "alloy", "echo", "fable", "onyx", "nova", "shimmer") */
    voice: string;
    /** Model name (e.g., "tts-1", "tts-1-hd") */
    model?: string;
}
