// This file was auto-generated by Fern from our API Definition.

import type * as Agora from "../index.js";

/**
 * OpenAI ASR configuration parameters.
 */
export interface OpenAiAsrParams {
    /** OpenAI API key */
    api_key: string;
    input_audio_transcription: Agora.OpenAiInputAudioTranscription;
    /** Accepts any additional properties */
    [key: string]: any;
}
