// This file was auto-generated by Fern from our API Definition.

import type * as Agora from "../index.js";

/**
 * OpenAI ASR configuration.
 */
export interface OpenAiAsr {
    language?: Agora.AsrLanguage;
    params: Agora.OpenAiAsrParams;
    /** Accepts any additional properties */
    [key: string]: any;
}
