// This file was auto-generated by Fern from our API Definition.

/**
 * OpenAI audio transcription configuration.
 */
export interface OpenAiInputAudioTranscription {
    /** OpenAI ASR model to use for transcription */
    model: string;
    /** Prompt that guides the transcription process */
    prompt: string;
    /** Language code to use for transcription */
    language: string;
    /** Accepts any additional properties */
    [key: string]: any;
}
