// This file was auto-generated by Fern from our API Definition.

/**
 * Rime TTS configuration parameters.
 */
export interface RimeTtsParams {
    /** Rime API key */
    api_key: string;
    /** Rime speaker ID */
    speaker: string;
    /** Rime TTS model ID */
    modelId: string;
    /** WebSocket URL for the Rime streaming API */
    base_url?: string;
    /** Accepts any additional properties */
    [key: string]: any;
}
