// This file was auto-generated by Fern from our API Definition.

import type * as Agora from "../index.js";

/**
 * Sarvam ASR configuration.
 */
export interface SarvamAsr {
    language?: Agora.AsrLanguage;
    params: Agora.SarvamAsrParams;
    /** Accepts any additional properties */
    [key: string]: any;
}
