// This file was auto-generated by Fern from our API Definition.

/**
 * Sarvam ASR configuration parameters.
 */
export interface SarvamAsrParams {
    /** Sarvam API key */
    api_key: string;
    /** Language code for transcription. Set to unknown for automatic language detection. */
    language: string;
    /** Accepts any additional properties */
    [key: string]: any;
}
