// This file was auto-generated by Fern from our API Definition.

/**
 * SenseTime Avatar configuration parameters.
 */
export interface SensetimeAvatarParams {
    /** Agora token used by the avatar service. */
    agora_token: string;
    /** Numeric Agora UID string used by the avatar service. */
    agora_uid: string;
    /** SenseTime application ID. */
    appId: string;
    /** SenseTime application key. */
    app_key: string;
    /** SenseTime scene configuration list. */
    sceneList: SensetimeAvatarParams.SceneList.Item[];
    /** Accepts any additional properties */
    [key: string]: any;
}

export namespace SensetimeAvatarParams {
    export type SceneList = SceneList.Item[];

    export namespace SceneList {
        export interface Item {
            digital_role?: Item.DigitalRole;
            /** Accepts any additional properties */
            [key: string]: any;
        }

        export namespace Item {
            export interface DigitalRole {
                /** SenseTime face feature identifier. */
                face_feature_id?: string;
                position?: DigitalRole.Position;
                /** Avatar model package URL. */
                url?: string;
                /** Accepts any additional properties */
                [key: string]: any;
            }

            export namespace DigitalRole {
                export interface Position {
                    /** Avatar x position. */
                    x?: number;
                    /** Avatar y position. */
                    y?: number;
                    /** Accepts any additional properties */
                    [key: string]: any;
                }
            }
        }
    }
}
