// This file was auto-generated by Fern from our API Definition.

/**
 * Spatius Avatar configuration parameters.
 */
export interface SpatiusAvatarParams {
    /** Spatius API key. */
    spatius_api_key: string;
    /** Spatius application ID. */
    spatius_app_id: string;
    /** Spatius avatar ID. */
    spatius_avatar_id: string;
    /** Agora UID used by the avatar service. */
    agora_uid: string;
    /** RTC token generated for `agora_uid` in the target channel. */
    agora_token?: string | null;
    /** Spatius service region, for example `cn-beijing`. */
    region?: string | null;
    /** Audio sample rate in Hz. Recommended to match the TTS sample rate. */
    sample_rate?: number | null;
    /** Spatius session validity duration in minutes. Defaults to 30. */
    session_expire_minutes?: number | null;
    /** Accepts any additional properties */
    [key: string]: any;
}
