// This file was auto-generated by Fern from our API Definition.

/**
 * Speechmatics ASR configuration parameters.
 */
export interface SpeechmaticsAsrParams {
    /** Speechmatics API key */
    api_key: string;
    /** Language code to use for transcription */
    language: string;
    /** WebSocket URL for the Speechmatics streaming API */
    uri?: string | null;
    /** Accepts any additional properties */
    [key: string]: any;
}
