// This file was auto-generated by Fern from our API Definition.

import type * as Agora from "../index.js";

/**
 * Speechmatics ASR configuration.
 */
export interface SpeechmaticsAsr {
    language?: Agora.AsrLanguage;
    params: Agora.SpeechmaticsAsrParams;
    /** Accepts any additional properties */
    [key: string]: any;
}
