// This file was auto-generated by Fern from our API Definition.

/**
 * StepFun TTS configuration parameters.
 */
export interface StepfunTtsParams {
    /** StepFun API key. */
    api_key: string;
    /** StepFun model identifier. */
    model: string;
    /** StepFun voice identifier. */
    voice_id: string;
    /** Accepts any additional properties */
    [key: string]: any;
}
