// This file was auto-generated by Fern from our API Definition.

/**
 * Error response returned when a Telephony or Phone Number Management API request fails.
 *
 * The response body includes `error_type` and `description` fields (not the Agent Management `detail`/`reason` shape).
 */
export interface TelephonyErrorResponse {
    /** The type of error that occurred. */
    error_type?: string;
    /** A detailed description of the error. */
    description?: string;
}
