// This file was auto-generated by Fern from our API Definition.

import type * as Agora from "../index.js";

/**
 * Tencent ASR configuration.
 */
export interface TencentAsr {
    language?: Agora.AsrLanguage;
    params: Agora.TencentAsrParams;
    /** Accepts any additional properties */
    [key: string]: any;
}
