// This file was auto-generated by Fern from our API Definition.

/**
 * Tencent TTS configuration parameters.
 */
export interface TencentTtsParams {
    /** Tencent Cloud application ID. */
    app_id: string;
    /** Tencent Cloud secret ID. */
    secret_id: string;
    /** Tencent Cloud secret key. */
    secret_key: string;
    /** Tencent voice type identifier. */
    voice_type: number;
    /** Volume setting. */
    volume?: number;
    /** Speech speed setting. */
    speed?: number;
    /** Emotion category. */
    emotion_category?: string;
    /** Emotion intensity. */
    emotion_intensity?: number;
    /** Accepts any additional properties */
    [key: string]: any;
}
