// This file was auto-generated by Fern from our API Definition.

/**
 * Tencent ASR configuration parameters.
 */
export interface TencentAsrParams {
    /** Tencent ASR secret key. */
    key: string;
    /** Tencent Cloud application ID. */
    app_id: string;
    /** Tencent ASR secret. */
    secret: string;
    /** Tencent ASR engine model type. */
    engine_model_type: string;
    /** Tencent ASR voice session identifier. */
    voice_id: string;
    /** Accepts any additional properties */
    [key: string]: any;
}
