// This file was auto-generated by Fern from our API Definition.

import type * as Agora from "../index.js";

export type Tts =
    | Agora.Tts.Tencent
    | Agora.Tts.Bytedance
    | Agora.Tts.Microsoft
    | Agora.Tts.Elevenlabs
    | Agora.Tts.Minimax
    | Agora.Tts.Murf
    | Agora.Tts.Cartesia
    | Agora.Tts.Openai
    | Agora.Tts.Humeai
    | Agora.Tts.Rime
    | Agora.Tts.Fishaudio
    | Agora.Tts.Google
    | Agora.Tts.Amazon
    | Agora.Tts.Sarvam
    | Agora.Tts.Generic
    | Agora.Tts.Xai
    | Agora.Tts.Deepgram
    | Agora.Tts.Cosyvoice
    | Agora.Tts.BytedanceDuplex
    | Agora.Tts.Stepfun;

export namespace Tts {
    export interface Tencent extends Agora.TencentTts {
        vendor: "tencent";
    }

    export interface Bytedance extends Agora.BytedanceTts {
        vendor: "bytedance";
    }

    export interface Microsoft extends Agora.MicrosoftTts {
        vendor: "microsoft";
    }

    export interface Elevenlabs extends Agora.ElevenLabsTts {
        vendor: "elevenlabs";
    }

    export interface Minimax extends Agora.MinimaxTts {
        vendor: "minimax";
    }

    export interface Murf extends Agora.MurfTts {
        vendor: "murf";
    }

    export interface Cartesia extends Agora.CartesiaTts {
        vendor: "cartesia";
    }

    export interface Openai extends Agora.OpenAiTts {
        vendor: "openai";
    }

    export interface Humeai extends Agora.HumeAiTts {
        vendor: "humeai";
    }

    export interface Rime extends Agora.RimeTts {
        vendor: "rime";
    }

    export interface Fishaudio extends Agora.FishAudioTts {
        vendor: "fishaudio";
    }

    export interface Google extends Agora.GoogleTts {
        vendor: "google";
    }

    export interface Amazon extends Agora.AmazonTts {
        vendor: "amazon";
    }

    export interface Sarvam extends Agora.SarvamTts {
        vendor: "sarvam";
    }

    export interface Generic extends Agora.GenericTts {
        vendor: "generic";
    }

    export interface Xai extends Agora.XAiTts {
        vendor: "xai";
    }

    export interface Deepgram extends Agora.DeepgramTts {
        vendor: "deepgram";
    }

    export interface Cosyvoice extends Agora.CosyvoiceTts {
        vendor: "cosyvoice";
    }

    export interface BytedanceDuplex extends Agora.BytedanceDuplexTts {
        vendor: "bytedance_duplex";
    }

    export interface Stepfun extends Agora.StepfunTts {
        vendor: "stepfun";
    }
}
