// This file was auto-generated by Fern from our API Definition.

/**
 * xAI ASR configuration parameters.
 */
export interface XAiAsrParams {
    /** xAI API key */
    api_key: string;
    /** WebSocket endpoint URL for the xAI streaming STT API. Defaults to `wss://api.x.ai/v1/stt`. */
    base_url?: string | null;
    /** Audio sample rate in Hz. */
    sample_rate?: number | null;
    /** Language code for speech recognition. */
    language?: string | null;
    /** Accepts any additional properties */
    [key: string]: any;
}
