// This file was auto-generated by Fern from our API Definition.

import type * as Agora from "../index.js";

/**
 * xAI ASR configuration.
 */
export interface XAiAsr {
    language?: Agora.AsrLanguage;
    params: Agora.XAiAsrParams;
    /** Accepts any additional properties */
    [key: string]: any;
}
