// This file was auto-generated by Fern from our API Definition.

/**
 * xAI TTS configuration parameters.
 */
export interface XAiTtsParams {
    /** xAI API key. */
    api_key: string;
    /** xAI voice identifier. */
    voice_id?: string | null;
    /** BCP-47 language code for speech synthesis. */
    language: string;
    /** Audio sample rate in Hz. */
    sample_rate?: number | null;
    /** Accepts any additional properties */
    [key: string]: any;
}
