// This file was auto-generated by Fern from our API Definition.

/**
 * iFlytek dialect ASR configuration parameters.
 */
export interface XfyunDialectAsrParams {
    /** iFlytek dialect application ID. */
    app_id: string;
    /** iFlytek access key ID. */
    access_key_id: string;
    /** iFlytek access key secret. */
    access_key_secret: string;
    /** Dialect recognition language code. */
    language: string;
    /** Accepts any additional properties */
    [key: string]: any;
}
