// This file was auto-generated by Fern from our API Definition.

import type * as Agora from "../index.js";

/**
 * iFlytek ASR configuration.
 */
export interface XfyunAsr {
    language?: Agora.AsrLanguage;
    params: Agora.XfyunAsrParams;
    /** Accepts any additional properties */
    [key: string]: any;
}
