// This file was auto-generated by Fern from our API Definition.

import type * as Agora from "../index.js";

/**
 * iFlytek large-model ASR configuration.
 */
export interface XfyunBigmodelAsr {
    language?: Agora.AsrLanguage;
    params: Agora.XfyunBigmodelAsrParams;
    /** Accepts any additional properties */
    [key: string]: any;
}
