// This file was auto-generated by Fern from our API Definition.

import type * as Agora from "../index.js";

/**
 * iFlytek dialect ASR configuration.
 */
export interface XfyunDialectAsr {
    language?: Agora.AsrLanguage;
    params: Agora.XfyunDialectAsrParams;
    /** Accepts any additional properties */
    [key: string]: any;
}
