// This file was auto-generated by Fern from our API Definition.

/**
 * iFlytek large-model ASR configuration parameters.
 */
export interface XfyunBigmodelAsrParams {
    /** iFlytek large-model API key. */
    api_key: string;
    /** iFlytek large-model application ID. */
    app_id: string;
    /** iFlytek large-model API secret. */
    api_secret: string;
    /** iFlytek language family name. */
    language_name: string;
    /** iFlytek language mode. */
    language: string;
    /** Accepts any additional properties */
    [key: string]: any;
}
