// This file was auto-generated by Fern from our API Definition.

/**
 * iFlytek ASR configuration parameters.
 */
export interface XfyunAsrParams {
    /** iFlytek API key. */
    api_key: string;
    /** iFlytek application ID. */
    app_id: string;
    /** iFlytek API secret. */
    api_secret: string;
    /** iFlytek language code. */
    language: string;
    /** Accepts any additional properties */
    [key: string]: any;
}
