// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         appid: "appid",
 *         agentId: "agentId",
 *         text: "The user just clicked the purchase button.",
 *         on_listening_action: "inject",
 *         on_thinking_action: "interrupt",
 *         on_speaking_action: "ignore",
 *         interruptable: true,
 *         metadata: {
 *             "publisher": "user123",
 *             "model": "deepseek-r1"
 *         }
 *     }
 */
export interface AgentThinkRequest {
    /** The App ID of the project. */
    appid: string;
    /** The agent instance ID you obtained after successfully calling `join` to start a conversational AI agent. */
    agentId: string;
    /** The custom instruction text to inject into the current conversation pipeline. The system processes this as user input. */
    text: string;
    /**
     * The action to take when the agent is in a listening state:
     * - `inject`: Inject the custom text instruction into the current turn without interrupting it.
     * - `ignore`: Ignore the request.
     */
    on_listening_action?: AgentThinkRequest.OnListeningAction;
    /**
     * The action to take when the agent is in a thinking state:
     * - `interrupt`: Interrupt the current state and start a new conversation turn.
     * - `ignore`: Ignore the request.
     */
    on_thinking_action?: AgentThinkRequest.OnThinkingAction;
    /**
     * The action to take when the agent is in a speaking state:
     * - `interrupt`: Interrupt the current state and start a new conversation turn.
     * - `ignore`: Ignore the request.
     */
    on_speaking_action?: AgentThinkRequest.OnSpeakingAction;
    /**
     * Whether user speech can interrupt the injected instruction:
     * - `true`: User speech can interrupt the instruction.
     * - `false`: User speech cannot interrupt the instruction.
     */
    interruptable?: boolean;
    /** Custom metadata in key-value pair format. Use this field to pass additional business information such as identifiers or model references. */
    metadata?: Record<string, string>;
}

export namespace AgentThinkRequest {
    /**
     * The action to take when the agent is in a listening state:
     * - `inject`: Inject the custom text instruction into the current turn without interrupting it.
     * - `ignore`: Ignore the request.
     */
    export const OnListeningAction = {
        Inject: "inject",
        Ignore: "ignore",
    } as const;
    export type OnListeningAction = (typeof OnListeningAction)[keyof typeof OnListeningAction];
    /**
     * The action to take when the agent is in a thinking state:
     * - `interrupt`: Interrupt the current state and start a new conversation turn.
     * - `ignore`: Ignore the request.
     */
    export const OnThinkingAction = {
        Interrupt: "interrupt",
        Ignore: "ignore",
    } as const;
    export type OnThinkingAction = (typeof OnThinkingAction)[keyof typeof OnThinkingAction];
    /**
     * The action to take when the agent is in a speaking state:
     * - `interrupt`: Interrupt the current state and start a new conversation turn.
     * - `ignore`: Ignore the request.
     */
    export const OnSpeakingAction = {
        Interrupt: "interrupt",
        Ignore: "ignore",
    } as const;
    export type OnSpeakingAction = (typeof OnSpeakingAction)[keyof typeof OnSpeakingAction];
}
