// This file was auto-generated by Fern from our API Definition.

export interface AgentThinkAgentManagementResponse {
    /** Unique identifier of the agent instance. */
    agent_id?: string;
    /** The name of the RTC channel where the agent is located. */
    channel?: string;
    /** Unix timestamp in seconds when the think request was processed. */
    start_ts?: number;
}
