// This file was auto-generated by Fern from our API Definition.

export interface GetAgentsResponse {
    /** Request message. */
    message?: string;
    /** Agent creation timestamp. */
    start_ts?: number;
    /** Agent stop timestamp. */
    stop_ts?: number;
    /**
     * Current status:
     * - `IDLE` (0): Agent is idle.
     * - `STARTING` (1): The agent is being started.
     * - `RUNNING` (2): The agent is running.
     * - `STOPPING` (3): The agent is stopping.
     * - `STOPPED` (4): The agent has exited.
     * - `FAILED` (6): The agent failed to execute.
     */
    status?: GetAgentsResponse.Status;
    /** Unique id of the agent instance */
    agent_id?: string;
}

export namespace GetAgentsResponse {
    /**
     * Current status:
     * - `IDLE` (0): Agent is idle.
     * - `STARTING` (1): The agent is being started.
     * - `RUNNING` (2): The agent is running.
     * - `STOPPING` (3): The agent is stopping.
     * - `STOPPED` (4): The agent has exited.
     * - `FAILED` (6): The agent failed to execute.
     */
    export const Status = {
        Idle: "IDLE",
        Starting: "STARTING",
        Running: "RUNNING",
        Stopping: "STOPPING",
        Stopped: "STOPPED",
        Failed: "FAILED",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
