// This file was auto-generated by Fern from our API Definition.

export interface GetTurnsAgentsResponse {
    /** The unique identifier of the agent. */
    agent_id?: string;
    /** The name of the agent. */
    name?: string;
    /** The name of the RTC channel the agent joined. */
    channel?: string;
    /** The total number of dialogue turns in the current session. */
    total_turn_count?: number;
    /** Pagination information. */
    pagination?: GetTurnsAgentsResponse.Pagination;
    /** A list of conversation turns for the agent session. */
    turns?: GetTurnsAgentsResponse.Turns.Item[];
}

export namespace GetTurnsAgentsResponse {
    /**
     * Pagination information.
     */
    export interface Pagination {
        /** The current page number; starts from 1. */
        page_index?: number;
        /** The total number of pages. */
        total_pages?: number;
        /** True if the current page is the last page. */
        is_last_page?: boolean;
    }

    export type Turns = Turns.Item[];

    export namespace Turns {
        export interface Item {
            /** The unique identifier of the agent. */
            agent_id?: string;
            /** The name of the RTC channel the agent joined. */
            channel?: string;
            /** The sequential index of the turn within the session. Starts at `1`. */
            turn_id?: number;
            /** Details about the start of the turn. */
            start?: Item.Start;
            /** Details about the end of the turn. */
            end?: Item.End;
            /** Latency metrics for the turn. */
            metrics?: Item.Metrics;
        }

        export namespace Item {
            /**
             * Details about the start of the turn.
             */
            export interface Start {
                /** The Unix timestamp in milliseconds (UTC time) when the turn started. */
                start_at?: number;
                /**
                 * The type of event that initiated the turn.
                 * - `voice_input`: The turn was initiated by user voice input.
                 * - `greeting`: The turn was initiated by an agent greeting.
                 * - `silence_timeout`: The turn was initiated due to a silence timeout.
                 * - `api_speak`: The turn was initiated by a call to the speak API.
                 */
                type?: Start.Type;
                /** Additional context about the turn start event. Included fields depend on the value of the `type` field. */
                metadata?: Start.Metadata;
            }

            export namespace Start {
                /**
                 * The type of event that initiated the turn.
                 * - `voice_input`: The turn was initiated by user voice input.
                 * - `greeting`: The turn was initiated by an agent greeting.
                 * - `silence_timeout`: The turn was initiated due to a silence timeout.
                 * - `api_speak`: The turn was initiated by a call to the speak API.
                 */
                export const Type = {
                    VoiceInput: "voice_input",
                    Greeting: "greeting",
                    SilenceTimeout: "silence_timeout",
                    ApiSpeak: "api_speak",
                } as const;
                export type Type = (typeof Type)[keyof typeof Type];

                /**
                 * Additional context about the turn start event. Included fields depend on the value of the `type` field.
                 */
                export interface Metadata {
                    /** The duration of the user's voice input in milliseconds. Included only when `type` is `voice_input`. */
                    speech_duration_ms?: number;
                    /** The minimum voice duration in milliseconds required to trigger an interruption. Included only when `type` is `voice_input`. */
                    interrupt_duration_ms?: number;
                    /** The index of the current greeting occurrence. Included only when `type` is `greeting`. */
                    greeting_nth?: number;
                    /**
                     * The action taken in response to the silence timeout. Included only when `type` is `silence_timeout`.
                     * - `speak`: Plays the silence prompt message to the user.
                     * - `think`: Appends the silence message to the conversation context and passes it to the LLM.
                     */
                    action?: string;
                    /**
                     * The transport protocol used to deliver the speak request. Included only when `type` is `api_speak`.
                     * - `http`: Delivered over HTTP.
                     * - `rtm`: Delivered through the RTM Presence channel.
                     */
                    transport?: string;
                }
            }

            /**
             * Details about the end of the turn.
             */
            export interface End {
                /** The Unix timestamp in milliseconds (UTC time) when the turn ended. */
                end_at?: number;
                /**
                 * The type of event that ended the turn.
                 * - `ok`: The turn ended normally.
                 * - `interrupted`: The turn was interrupted.
                 * - `ignored`: The turn was ignored.
                 * - `error`: The turn ended due to an error.
                 */
                type?: End.Type;
                /** Additional context about the turn end event. Included fields depend on the value of the `type` field. */
                metadata?: End.Metadata;
            }

            export namespace End {
                /**
                 * The type of event that ended the turn.
                 * - `ok`: The turn ended normally.
                 * - `interrupted`: The turn was interrupted.
                 * - `ignored`: The turn was ignored.
                 * - `error`: The turn ended due to an error.
                 */
                export const Type = {
                    Ok: "ok",
                    Interrupted: "interrupted",
                    Ignored: "ignored",
                    Error: "error",
                } as const;
                export type Type = (typeof Type)[keyof typeof Type];

                /**
                 * Additional context about the turn end event. Included fields depend on the value of the `type` field.
                 */
                export interface Metadata {
                    /** The audio playback duration in milliseconds. Included only when `type` is `ok`. */
                    playback_duration_ms?: number;
                    /**
                     * The cause of the turn ending.
                     *
                     * When `type` is `interrupted`, possible values are:
                     * - `start_of_speech`: A new voice input interrupted the turn.
                     * - `api_speak`: The turn was interrupted by a call to the speak API.
                     * - `api_interrupt`: The turn was interrupted by a call to the interrupt API.
                     * - `api_leave`: The turn was interrupted because the agent left the channel.
                     *
                     * When `type` is `ignored`, possible values are:
                     * - `semantic`: The turn was ignored because semantic end-of-speech detection determined no response was required. Applies when `turn_detection.config.end_of_speech.mode` is set to `semantic`.
                     * - `keywords`: The turn was ignored because the start keyword was not detected. Applies when `turn_detection.config.start_of_speech.mode` is set to `keywords`.
                     * - `disable`: The turn was ignored because interruption is disabled for this turn.
                     */
                    caused_by?: string;
                    /**
                     * The transport protocol used to deliver the request. Included only when `caused_by` is `api_speak` or `api_interrupt`.
                     * - `http`: Delivered over HTTP.
                     * - `rtm`: Delivered through the RTM Presence channel.
                     */
                    transport?: string;
                    /**
                     * The error type. Included only when `type` is `error`.
                     * - `LLM_REQUEST_ERR`: LLM request error.
                     * - `INTERNAL_ERR`: Internal error.
                     */
                    reason?: string;
                    /** Additional error details. Included only when `type` is `error`. */
                    details?: string;
                }
            }

            /**
             * Latency metrics for the turn.
             */
            export interface Metrics {
                /** The end-to-end latency in milliseconds for the turn. */
                e2e_latency_ms?: number;
                /** A breakdown of latency by segment. */
                segmented_latency_ms?: Metrics.SegmentedLatencyMs.Item[];
            }

            export namespace Metrics {
                export type SegmentedLatencyMs = SegmentedLatencyMs.Item[];

                export namespace SegmentedLatencyMs {
                    export interface Item {
                        /**
                         * The name of the latency segment.
                         *
                         * When the LLM input modality is `text`, the returned segments are:
                         * - `algorithm_processing`: Algorithm processing delay.
                         * - `asr_ttlw`: The ASR Time To Last Word (TTLW) in milliseconds. Represents the delay from when the user finishes speaking to when the ASR module outputs the last word.
                         * - `llm_ttft`: The LLM Time To First Token (TTFT) in milliseconds. Represents the delay from when the user finishes speaking to when the LLM outputs the first token.
                         * - `llm_ftfs`: The LLM First Token To First Sentence (FTFS) in milliseconds. Represents the delay from when the LLM outputs the first token to when it outputs the first complete sentence.
                         * - `tts_ttfb`: The TTS Time To First Byte (TTFB) in milliseconds. Represents the delay from when the TTS module receives a text request to when it outputs the first audio byte.
                         * - `transport`: Network transmission delay in milliseconds. Not returned when the user is connected using the RTC Web SDK.
                         *
                         * When the LLM input modality is `audio`, the returned segments are:
                         * - `algorithm_processing`: Algorithm processing delay.
                         * - `asr_ttlw`: The ASR Time To Last Word (TTLW) in milliseconds. Represents the delay from when the user finishes speaking to when the ASR module outputs the last word.
                         * - `llm_ttfa`: The LLM Time To First Audio Byte (TTFA) in milliseconds. Represents the delay from when the user finishes speaking to when the LLM outputs the first audio byte.
                         * - `transport`: Network transmission delay in milliseconds. Not returned when the user is connected using the RTC Web SDK.
                         */
                        name?: string;
                        /** The latency in milliseconds for the segment. */
                        latency?: number;
                    }
                }
            }
        }
    }
}
