// This file was auto-generated by Fern from our API Definition.

export interface InterruptAgentsResponse {
    /** Unique id of the agent instance */
    agent_id?: string;
    /** The name of the channel */
    channel?: string;
    /** Unix timestamp in seconds when the interrupt request was processed. */
    start_ts?: number;
}
