// This file was auto-generated by Fern from our API Definition.

export interface ListAgentsResponse {
    /** Agent data. */
    data: ListAgentsResponse.Data;
    /** Returns meta information about the list. */
    meta?: ListAgentsResponse.Meta;
    /** Request status. */
    status?: string;
}

export namespace ListAgentsResponse {
    /**
     * Agent data.
     */
    export interface Data {
        /** The number of agents returned. */
        count?: number;
        /** A list of agents that meets the criteria. */
        list: Data.List.Item[];
    }

    export namespace Data {
        export type List = List.Item[];

        export namespace List {
            export interface Item {
                /** Agent creation timestamp. */
                start_ts?: number;
                /** The current state of the agent. */
                status?: Item.Status;
                /** The agent ID. */
                agent_id?: string;
            }

            export namespace Item {
                /** The current state of the agent. */
                export const Status = {
                    Idle: "IDLE",
                    Starting: "STARTING",
                    Running: "RUNNING",
                    Stopping: "STOPPING",
                    Stopped: "STOPPED",
                    Failed: "FAILED",
                } as const;
                export type Status = (typeof Status)[keyof typeof Status];
            }
        }
    }

    /**
     * Returns meta information about the list.
     */
    export interface Meta {
        /** Paging cursor. */
        cursor?: string;
        /** The total number of agents that meet the query conditions. */
        total?: number;
    }
}
