// This file was auto-generated by Fern from our API Definition.

import * as dns from "dns";
import { promisify } from "util";

const lookupHost = promisify(dns.lookup);

/**
 * Area represents the global regions where the Open API gateway endpoint is located
 */
export enum Area {
    Unknown = 0,
    /** US represents the western and eastern regions of the United States */
    US = 1,
    /** EU represents the western and central regions of Europe */
    EU = 2,
    /** AP represents the southeastern and northeastern regions of Asia-Pacific */
    AP = 3,
    /** CN represents the eastern and northern regions of Chinese mainland */
    CN = 4,
}

export const ChineseMainlandMajorDomain = "sd-rtn.com";
export const OverseaMajorDomain = "agora.io";

export const GlobalDomainPrefix = "api";

export const USWestRegionDomainPrefix = "api-us-west-1";
export const USEastRegionDomainPrefix = "api-us-east-1";

export const APSoutheastRegionDomainPrefix = "api-ap-southeast-1";
export const APNortheastRegionDomainPrefix = "api-ap-northeast-1";

export const EUWestRegionDomainPrefix = "api-eu-west-1";
export const EUCentralRegionDomainPrefix = "api-eu-central-1";

export const CNEastRegionDomainPrefix = "api-cn-east-1";
export const CNNorthRegionDomainPrefix = "api-cn-north-1";

export const APIPath = "/api/conversational-ai-agent";

/**
 * Domain contains the regional prefixes and domain suffixes for an area
 */
export interface Domain {
    regionDomainPrefixes: string[];
    majorDomainSuffixes: string[];
}

/**
 * RegionDomain maps areas to their domain configurations
 */
export const RegionDomain: Record<Area, Domain> = {
    [Area.Unknown]: {
        regionDomainPrefixes: [],
        majorDomainSuffixes: [],
    },
    [Area.US]: {
        regionDomainPrefixes: [USWestRegionDomainPrefix, USEastRegionDomainPrefix],
        majorDomainSuffixes: [OverseaMajorDomain, ChineseMainlandMajorDomain],
    },
    [Area.EU]: {
        regionDomainPrefixes: [EUWestRegionDomainPrefix, EUCentralRegionDomainPrefix],
        majorDomainSuffixes: [OverseaMajorDomain, ChineseMainlandMajorDomain],
    },
    [Area.AP]: {
        regionDomainPrefixes: [APSoutheastRegionDomainPrefix, APNortheastRegionDomainPrefix],
        majorDomainSuffixes: [OverseaMajorDomain, ChineseMainlandMajorDomain],
    },
    [Area.CN]: {
        regionDomainPrefixes: [CNEastRegionDomainPrefix, CNNorthRegionDomainPrefix],
        majorDomainSuffixes: [ChineseMainlandMajorDomain, OverseaMajorDomain],
    },
};

/**
 * Resolver is an interface for resolving the best domain
 */
export interface Resolver {
    resolve(domains: string[], regionPrefix: string, signal?: AbortSignal): Promise<string>;
}

/**
 * Default DNS-based resolver implementation
 */
class ResolverImpl implements Resolver {
    async resolve(domains: string[], regionPrefix: string, signal?: AbortSignal): Promise<string> {
        const results = await Promise.allSettled(
            domains.map(async (domain) => {
                if (signal?.aborted) {
                    throw new Error("Aborted");
                }
                const url = `${regionPrefix}.${domain}`;
                await lookupHost(url);
                return domain;
            }),
        );

        for (const result of results) {
            if (result.status === "fulfilled") {
                return result.value;
            }
        }

        throw new Error("query all dns failed");
    }
}

const UPDATE_DURATION_MS = 30 * 1000; // 30 seconds

/**
 * Pool manages a pool of regional URLs with automatic cycling and domain selection
 */
export class Pool {
    private domainArea: Area;
    private domainSuffixes: string[];
    private currentDomain: string;
    private regionPrefixes: string[];
    private currentRegionPrefixes: string[];
    private resolver: Resolver;
    private lastUpdate: number = 0;

    constructor(domainArea: Area) {
        const domainConfig = RegionDomain[domainArea];
        if (!domainConfig || domainConfig.regionDomainPrefixes.length === 0) {
            throw new Error("invalid domain area");
        }

        this.domainArea = domainArea;
        this.domainSuffixes = [...domainConfig.majorDomainSuffixes];
        this.regionPrefixes = [...domainConfig.regionDomainPrefixes];
        this.currentRegionPrefixes = [...this.regionPrefixes];
        this.currentDomain = this.domainSuffixes[0];
        this.resolver = new ResolverImpl();
    }

    private domainNeedUpdate(): boolean {
        return Date.now() - this.lastUpdate > UPDATE_DURATION_MS;
    }

    /**
     * SelectBestDomain uses DNS resolution to select the best available domain
     */
    async selectBestDomain(signal?: AbortSignal): Promise<void> {
        if (!this.domainNeedUpdate()) {
            return;
        }

        const domain = await this.resolver.resolve(this.domainSuffixes, this.currentRegionPrefixes[0], signal);
        this.selectDomain(domain);
    }

    /**
     * NextRegion cycles to the next region prefix in the pool
     */
    nextRegion(): void {
        this.currentRegionPrefixes = this.currentRegionPrefixes.slice(1);
        if (this.currentRegionPrefixes.length === 0) {
            this.currentRegionPrefixes = [...this.regionPrefixes];
        }
    }

    private selectDomain(domain: string): void {
        if (this.domainSuffixes.includes(domain)) {
            this.currentDomain = domain;
            this.lastUpdate = Date.now();
        }
    }

    /**
     * GetCurrentURL returns the current URL based on the selected region and domain
     */
    getCurrentURL(): string {
        const currentRegion = this.currentRegionPrefixes[0];
        const currentDomain = this.currentDomain;
        return `https://${currentRegion}.${currentDomain}${APIPath}`;
    }

    /**
     * Get the current area
     */
    getArea(): Area {
        return this.domainArea;
    }
}

/**
 * Creates a new Pool for the specified area
 */
export function createPool(area: Area): Pool {
    return new Pool(area);
}
