// This file was auto-generated by Fern from our API Definition.

import { AgoraClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("AgentManagementClient", () => {
    test("agent-think", async () => {
        const server = mockServerPool.createServer();
        const client = new AgoraClient({
            username: "test",
            password: "test",
            authorization: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {
            text: "The user just clicked the purchase button.",
            on_listening_action: "inject",
            on_thinking_action: "interrupt",
            on_speaking_action: "ignore",
            interruptable: true,
            metadata: { publisher: "user123", model: "deepseek-r1" },
        };
        const rawResponseBody = { agent_id: "1NT29XxxxxxxxxELWEHC8OS", channel: "test_channel", start_ts: 1744877089 };
        server
            .mockEndpoint()
            .post("/v2/projects/appid/agents/agentId/think")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.agentManagement.agentThink({
            appid: "appid",
            agentId: "agentId",
            text: "The user just clicked the purchase button.",
            on_listening_action: "inject",
            on_thinking_action: "interrupt",
            on_speaking_action: "ignore",
            interruptable: true,
            metadata: {
                publisher: "user123",
                model: "deepseek-r1",
            },
        });
        expect(response).toEqual({
            agent_id: "1NT29XxxxxxxxxELWEHC8OS",
            channel: "test_channel",
            start_ts: 1744877089,
        });
    });
});
