// This file was auto-generated by Fern from our API Definition.

import { AgoraClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("TelephonyClient", () => {
    test("list", async () => {
        const server = mockServerPool.createServer();
        const client = new AgoraClient({
            username: "test",
            password: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            data: {
                count: 1,
                list: [
                    {
                        to_number: "2222",
                        from_number: "111",
                        pipeline_id: "28",
                        type: "inbound",
                        agent_id: "A42AA22ATxxxxx4RH76AM92W",
                        channel: "channel_1111",
                        create_ts: 1758498988,
                        state: "answered",
                    },
                ],
            },
            meta: { cursor: "A42AA22AT45LDxxxxxH76AM92W", total: 1 },
            status: "ok",
        };
        server
            .mockEndpoint()
            .get("/v2/projects/appid/call")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const expected = {
            data: {
                count: 1,
                list: [
                    {
                        to_number: "2222",
                        from_number: "111",
                        pipeline_id: "28",
                        type: "inbound",
                        agent_id: "A42AA22ATxxxxx4RH76AM92W",
                        channel: "channel_1111",
                        create_ts: 1758498988,
                        state: "answered",
                    },
                ],
            },
            meta: {
                cursor: "A42AA22AT45LDxxxxxH76AM92W",
                total: 1,
            },
            status: "ok",
        };
        const page = await client.telephony.list({
            appid: "appid",
        });

        expect(expected.data.list).toEqual(page.data);
        expect(page.hasNextPage()).toBe(true);
        const nextPage = await page.getNextPage();
        expect(expected.data.list).toEqual(nextPage.data);
    });

    test("call (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgoraClient({
            username: "test",
            password: "test",
            authorization: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {
            name: "customer_service",
            sip: {
                to_number: "+19876543210",
                from_number: "+11234567890",
                rtc_uid: "100",
                rtc_token: "<agora_sip_rtc_token>",
            },
            pipeline_id: "fzufjlweixxxxnlp",
            properties: {
                channel: "<agora_channel>",
                token: "<agora_channel_token>",
                agent_rtc_uid: "111",
                remote_rtc_uids: ["100"],
            },
        };
        const rawResponseBody = { agent_id: "A42AK62PExxxxxxxx74LN47MF46E" };
        server
            .mockEndpoint()
            .post("/v2/projects/appid/call")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.telephony.call({
            appid: "appid",
            name: "customer_service",
            sip: {
                to_number: "+19876543210",
                from_number: "+11234567890",
                rtc_uid: "100",
                rtc_token: "<agora_sip_rtc_token>",
            },
            pipeline_id: "fzufjlweixxxxnlp",
            properties: {
                channel: "<agora_channel>",
                token: "<agora_channel_token>",
                agent_rtc_uid: "111",
                remote_rtc_uids: ["100"],
            },
        });
        expect(response).toEqual({
            agent_id: "A42AK62PExxxxxxxx74LN47MF46E",
        });
    });

    test("call (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgoraClient({
            username: "test",
            password: "test",
            authorization: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {
            name: "customer_service",
            sip: {
                to_number: "+19876543210",
                from_number: "+11234567890",
                rtc_uid: "100",
                rtc_token: "<agora_sip_rtc_token>",
            },
            properties: {
                idle_timeout: 120,
                llm: {
                    url: "https://api.openai.com/v1/chat/completions",
                    api_key: "<your_llm_key>",
                    system_messages: [{ role: "system", content: "You are a helpful chatbot." }],
                    max_history: 32,
                    greeting_message: "Hello, how can I assist you today?",
                    failure_message: "Please hold on a second.",
                    params: { model: "gpt-4o-mini" },
                },
                tts: {
                    vendor: "microsoft",
                    params: {
                        key: "<your_tts_api_key>",
                        region: "eastus",
                        voice_name: "en-US-AndrewMultilingualNeural",
                    },
                },
                asr: { language: "en-US" },
                channel: "<agora_channel>",
                token: "<agora_channel_token>",
                agent_rtc_uid: "111",
                remote_rtc_uids: ["100"],
            },
        };
        const rawResponseBody = { agent_id: "A42AK62PExxxxxxxx74LN47MF46E" };
        server
            .mockEndpoint()
            .post("/v2/projects/appid/call")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.telephony.call({
            appid: "appid",
            name: "customer_service",
            sip: {
                to_number: "+19876543210",
                from_number: "+11234567890",
                rtc_uid: "100",
                rtc_token: "<agora_sip_rtc_token>",
            },
            properties: {
                channel: "<agora_channel>",
                token: "<agora_channel_token>",
                agent_rtc_uid: "111",
                remote_rtc_uids: ["100"],
                idle_timeout: 120,
                llm: {
                    url: "https://api.openai.com/v1/chat/completions",
                    api_key: "<your_llm_key>",
                    system_messages: [
                        {
                            role: "system",
                            content: "You are a helpful chatbot.",
                        },
                    ],
                    max_history: 32,
                    greeting_message: "Hello, how can I assist you today?",
                    failure_message: "Please hold on a second.",
                    params: {
                        model: "gpt-4o-mini",
                    },
                },
                tts: {
                    vendor: "microsoft",
                    params: {
                        key: "<your_tts_api_key>",
                        region: "eastus",
                        voice_name: "en-US-AndrewMultilingualNeural",
                    },
                },
                asr: {
                    language: "en-US",
                },
            },
        });
        expect(response).toEqual({
            agent_id: "A42AK62PExxxxxxxx74LN47MF46E",
        });
    });

    test("get", async () => {
        const server = mockServerPool.createServer();
        const client = new AgoraClient({
            username: "test",
            password: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            to_number: "1300000000",
            from_number: "1330000000",
            pipeline_id: "28",
            type: "inbound",
            agent_id: "A42AA22AT45xxxxxxRH76AM92W",
            channel: "channel_1111",
            reason: "request",
            create_ts: 1758498988,
            state: "hangup",
            stop_ts: 1758498995,
        };
        server
            .mockEndpoint()
            .get("/v2/projects/appid/calls/agent_id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.telephony.get({
            appid: "appid",
            agent_id: "agent_id",
        });
        expect(response).toEqual({
            to_number: "1300000000",
            from_number: "1330000000",
            pipeline_id: "28",
            type: "inbound",
            agent_id: "A42AA22AT45xxxxxxRH76AM92W",
            channel: "channel_1111",
            reason: "request",
            create_ts: 1758498988,
            state: "hangup",
            stop_ts: 1758498995,
        });
    });

    test("hangup", async () => {
        const server = mockServerPool.createServer();
        const client = new AgoraClient({
            username: "test",
            password: "test",
            authorization: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = {};
        server
            .mockEndpoint()
            .post("/v2/projects/appid/calls/agent_id/hangup")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.telephony.hangup({
            appid: "appid",
            agent_id: "agent_id",
        });
        expect(response).toEqual({});
    });
});
