// This file was auto-generated by Fern from our API Definition.

import { Agent, type AgentOptions } from "./agentkit/Agent.js";
import { generateConvoAIToken } from "./agentkit/token.js";
import type { AgoraArea } from "./agentkit/area.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { AgoraClient as BaseAgoraClient } from "./Client.js";
import { type Area, Pool } from "./core/domain/index.js";
import { AgoraError } from "./errors/index.js";

/**
 * Auth mode for the client:
 * - `basic`: Customer ID + Secret for REST API (HTTP Basic Auth)
 * - `token`: Pre-built `agora token=<value>` auth header
 * - `app-credentials`: appId + appCertificate only; AgentSession generates
 *   a fresh ConvoAI token per API call
 */
export type AgoraAuthMode = "basic" | "token" | "app-credentials";

export declare namespace AgoraClient {
    export type Options<TArea extends AgoraArea = AgoraArea> = BaseOptions<TArea> & AuthOptions;

    interface BaseOptions<TArea extends AgoraArea = AgoraArea>
        extends Omit<BaseClientOptions, "baseUrl" | "environment" | "username" | "password" | "authorization"> {
        /** The area to use for regional URL selection */
        area: TArea;
        /** Agora App ID — used as the `appid` path parameter and for RTC token generation */
        appId: string;
        /** Agora App Certificate — used to sign RTC tokens. Keep this secret. */
        appCertificate: string;
    }

    /** Use Customer ID + Secret for REST API authentication (HTTP Basic Auth) */
    interface BasicAuthOptions {
        customerId: string;
        customerSecret: string;
        authToken?: never;
    }

    /** Use a pre-built Agora token for REST API authentication. Pass the raw token; the SDK sets `Authorization: agora token=<authToken>` automatically. */
    interface TokenAuthOptions {
        authToken: string;
        customerId?: never;
        customerSecret?: never;
    }

    /**
     * Use only appId + appCertificate. AgentSession generates a fresh
     * ConvoAI token per API call — no Customer Secret required.
     */
    interface AppCredentialsOptions {
        customerId?: never;
        customerSecret?: never;
        authToken?: never;
    }

    type AuthOptions = BasicAuthOptions | TokenAuthOptions | AppCredentialsOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * AgoraClient extends the base client with domain pool support for
 * regional URL cycling and automatic domain selection.
 *
 * Three authentication modes are supported:
 *
 * **App credentials (recommended)** — no Customer Secret needed; AgentSession
 * generates a short-lived ConvoAI token per API call:
 * ```typescript
 * const client = new AgoraClient({
 *     area: Area.US,
 *     appId: "your-app-id",
 *     appCertificate: "your-app-certificate",
 * });
 * ```
 *
 * **Token auth** — pass a raw Agora token; the SDK sets the `agora token=` header automatically:
 * ```typescript
 * const client = new AgoraClient({
 *     area: Area.US,
 *     appId: "your-app-id",
 *     appCertificate: "your-app-certificate",
 *     authToken: "<raw-token>",
 * });
 * ```
 *
 * **Basic auth** — Customer ID + Secret from Agora Console:
 * ```typescript
 * const client = new AgoraClient({
 *     area: Area.US,
 *     appId: "your-app-id",
 *     appCertificate: "your-app-certificate",
 *     customerId: "your-customer-id",
 *     customerSecret: "your-customer-secret",
 * });
 * ```
 */
export class AgoraClient<TArea extends AgoraArea = AgoraArea> extends BaseAgoraClient {
    protected readonly _pool: Pool;
    /** Agora App ID */
    public readonly appId: string;
    /** Agora App Certificate (used for RTC token signing) */
    public readonly appCertificate: string;
    /** The active authentication mode */
    public readonly authMode: AgoraAuthMode;
    /** The configured routing area */
    public readonly area: TArea;

    constructor(options: AgoraClient.Options<TArea>) {
        const pool = new Pool(options.area);

        let authMode: AgoraAuthMode;
        let username: string;
        let password: string;
        let authToken = "";

        const opts = options as AgoraClient.Options<TArea> & {
            customerId?: string;
            customerSecret?: string;
            authToken?: string;
        };

        if (opts.customerId != null && opts.customerSecret != null) {
            authMode = "basic";
            username = opts.customerId;
            password = opts.customerSecret;
        } else if (opts.customerId != null) {
            throw new Error("customerSecret is required when customerId is provided");
        } else if (opts.authToken != null) {
            authMode = "token";
            authToken = opts.authToken;
            username = "";
            password = "";
        } else {
            authMode = "app-credentials";
            username = "";
            password = "";
        }

        const { customerId: _cid, customerSecret: _cs, authToken: _at, ...rest } = opts;

        // _getCustomAuthorizationHeaders() in the generated client spreads { Authorization }
        // after _getAuthorizationHeader(), so it overrides the Basic header on every request.
        const authorization =
            authMode === "basic"
                ? `Basic ${Buffer.from(`${username}:${password}`).toString("base64")}`
                : authMode === "token"
                  ? `agora token=${authToken}`
                  : "";

        super({
            ...rest,
            username,
            password,
            authorization,
            baseUrl: () => pool.getCurrentURL(),
        });
        this._pool = pool;
        this.appId = options.appId;
        this.appCertificate = options.appCertificate;
        this.authMode = authMode;
        this.area = options.area as TArea;
    }

    /**
     * Create an {@link Agent} bound to this client.
     */
    public agent(options: Omit<AgentOptions<TArea>, "client"> = {}): Agent<number, TArea> {
        return new Agent({ ...options, client: this }) as Agent<number, TArea>;
    }

    /**
     * Get the underlying domain pool for advanced usage.
     * You can use this to manually cycle regions or select the best domain.
     */
    public get pool(): Pool {
        return this._pool;
    }

    /**
     * Cycle to the next region prefix in the pool.
     * Call this when a request fails to try a different region.
     */
    public nextRegion(): void {
        this._pool.nextRegion();
    }

    /**
     * Select the best domain using DNS resolution.
     * This is automatically called periodically, but you can call it manually.
     */
    public async selectBestDomain(signal?: AbortSignal): Promise<void> {
        await this._pool.selectBestDomain(signal);
    }

    /**
     * Get the current URL being used for requests.
     */
    public getCurrentURL(): string {
        return this._pool.getCurrentURL();
    }

    /**
     * Stop an agent by its ID.
     *
     * Use this when handling a stop request from your client app (e.g., an end-call
     * button) without holding an `AgentSession` reference. Create a client with the
     * same credentials used to start the agent and call this method.
     *
     * If the agent has already stopped (e.g., timed out or crashed), this method
     * returns successfully rather than throwing.
     *
     * @param agentId - The agent instance ID returned by `AgentSession.start()`
     *
     * @example
     * // End-call handler — no session reference needed
     * const client = new AgoraClient({ area: Area.US, appId: '...', appCertificate: '...' });
     * await client.stopAgent(agentId);
     */
    public async stopAgent(agentId: string): Promise<void> {
        let headers: Record<string, string> | undefined;
        if (this.authMode === "app-credentials") {
            const token = generateConvoAIToken({
                appId: this.appId,
                appCertificate: this.appCertificate,
                channelName: "stop",
                uid: 0,
            });
            headers = { Authorization: `agora token=${token}` };
        }

        try {
            await this.agents.stop({ appid: this.appId, agentId }, { headers });
        } catch (error) {
            if (error instanceof AgoraError && error.statusCode === 404) {
                return; // Agent already stopped — treat as success
            }
            throw error;
        }
    }
}
