// This file was auto-generated by Fern from our API Definition.

import { AgentManagementClient } from "./api/resources/agentManagement/client/Client.js";
import { AgentsClient } from "./api/resources/agents/client/Client.js";
import { PhoneNumbersClient } from "./api/resources/phoneNumbers/client/Client.js";
import { TelephonyClient } from "./api/resources/telephony/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { normalizeClientOptions } from "./BaseClient.js";

export declare namespace AgoraClient {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class AgoraClient {
    protected readonly _options: AgoraClient.Options;
    protected _agents: AgentsClient | undefined;
    protected _agentManagement: AgentManagementClient | undefined;
    protected _telephony: TelephonyClient | undefined;
    protected _phoneNumbers: PhoneNumbersClient | undefined;

    constructor(options: AgoraClient.Options) {
        this._options = normalizeClientOptions(options);
    }

    public get agents(): AgentsClient {
        if (this._agents == null) {
            this._agents = new AgentsClient(this._options);
        }

        return this._agents;
    }

    public get agentManagement(): AgentManagementClient {
        if (this._agentManagement == null) {
            this._agentManagement = new AgentManagementClient(this._options);
        }

        return this._agentManagement;
    }

    public get telephony(): TelephonyClient {
        if (this._telephony == null) {
            this._telephony = new TelephonyClient(this._options);
        }

        return this._telephony;
    }

    public get phoneNumbers(): PhoneNumbersClient {
        if (this._phoneNumbers == null) {
            this._phoneNumbers = new PhoneNumbersClient(this._options);
        }

        return this._phoneNumbers;
    }
}
