export * as Agora from "./api/index.js";
export { AgoraClient } from "./AgoraPoolClient.js";
export type { AgoraAuthMode } from "./AgoraPoolClient.js";
export type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
export { AgoraEnvironment } from "./environments.js";
export { AgoraError, AgoraTimeoutError } from "./errors/index.js";
export { Area } from "./core/domain/index.js";
export * from "./exports.js";

// Agentkit layer exports - clean, ergonomic API
export {
    Agent,
    AgentSession,
    ExpiresIn,
    generateRtcToken,
    generateConvoAIToken,
    isHeyGenAvatar,
    isLiveAvatarAvatar,
    isAkoolAvatar,
    isAnamAvatar,
    validateAvatarConfig,
    validateTtsSampleRate,
    toBaseAvatarConfig,
    // Base vendor classes
    BaseLLM,
    BaseTTS,
    BaseSTT,
    BaseMLLM,
    BaseAvatar,
    // LLM vendors
    OpenAI,
    AzureOpenAI,
    Anthropic,
    Gemini,
    // TTS vendors
    ElevenLabsTTS,
    MicrosoftTTS,
    OpenAITTS,
    CartesiaTTS,
    GoogleTTS,
    AmazonTTS,
    HumeAITTS,
    RimeTTS,
    FishAudioTTS,
    MiniMaxTTS,
    MurfTTS,
    SarvamTTS,
    // STT vendors
    SpeechmaticsSTT,
    DeepgramSTT,
    MicrosoftSTT,
    OpenAISTT,
    GoogleSTT,
    AmazonSTT,
    AssemblyAISTT,
    AresSTT,
    SarvamSTT,
    // MLLM vendors
    OpenAIRealtime,
    GeminiLive,
    VertexAI,
    // Avatar vendors
    HeyGenAvatar,
    LiveAvatarAvatar,
    AkoolAvatar,
    AnamAvatar,
} from "./agentkit/index.js";
export type {
    AgentsClient,
    AgentOptions,
    AgentSessionOptions,
    GenerateTokenOptions,
    GenerateConvoAITokenOptions,
    AgentSessionEvent,
    AgentSessionEventHandler,
    // Sample rate types
    SampleRate,
    ElevenLabsSampleRate,
    MicrosoftSampleRate,
    CartesiaSampleRate,
    HeyGenSampleRate,
    LiveAvatarSampleRate,
    AkoolSampleRate,
    // Clean type aliases
    LlmConfig,
    LlmStyle,
    LlmGreetingConfigs,
    LlmGreetingConfigsMode,
    McpServersItem,
    SttConfig,
    SttVendor,
    TtsConfig,
    MllmConfig,
    MllmVendor,
    AvatarConfig,
    AvatarVendor,
    TurnDetectionConfig,
    TurnDetectionNestedConfig,
    StartOfSpeechConfig,
    StartOfSpeechMode,
    StartOfSpeechVadConfig,
    StartOfSpeechKeywordsConfig,
    StartOfSpeechDisabledConfig,
    StartOfSpeechDisabledConfigStrategy,
    EndOfSpeechConfig,
    EndOfSpeechMode,
    EndOfSpeechVadConfig,
    EndOfSpeechSemanticConfig,
    TurnDetectionType,
    InterruptMode,
    Eagerness,
    SalConfig,
    SalMode,
    AdvancedFeatures,
    SessionParams,
    SilenceConfig,
    SilenceAction,
    FarewellConfig,
    ParametersDataChannel,
    GeofenceConfig,
    GeofenceArea,
    GeofenceExcludeArea,
    RtcConfig,
    FillerWordsConfig,
    FillerWordsTrigger,
    FillerWordsTriggerFixedTimeConfig,
    FillerWordsContent,
    FillerWordsContentStaticConfig,
    FillerWordsContentSelectionRule,
    Labels,
    AgentConfig,
    AgentConfigUpdate,
    SessionOptions,
    SessionStatus,
    SessionInfo,
    SessionListResponse,
    SessionSummary,
    ConversationHistory,
    ConversationTurn,
    ConversationRole,
    ConversationTurns,
    ConversationSessionTurn,
    SayOptions,
    SpeakPriority,
    // Strict avatar config types
    StrictAvatarConfig,
    HeyGenAvatarConfig,
    LiveAvatarAvatarConfig,
    AkoolAvatarConfig,
    AnamAvatarConfig,
    GenericAvatarConfig,
    // TTS vendor parameter types
    MicrosoftTts,
    MicrosoftTtsParams,
    ElevenLabsTts,
    ElevenLabsTtsParams,
    CartesiaTts,
    CartesiaTtsParams,
    OpenAiTts,
    OpenAiTtsParams,
    HumeAiTts,
    HumeAiTtsParams,
    RimeTts,
    RimeTtsParams,
    FishAudioTts,
    FishAudioTtsParams,
    GoogleTts,
    GoogleTtsParams,
    AmazonTts,
    AmazonTtsParams,
    MinimaxTts,
    MinimaxTtsParams,
    MurfTts,
    MurfTtsParams,
    SarvamTts,
    SarvamTtsParams,
    // Vendor option types
    OpenAIOptions,
    AzureOpenAIOptions,
    AnthropicOptions,
    GeminiOptions,
    ElevenLabsTTSOptions,
    MicrosoftTTSOptions,
    OpenAITTSOptions,
    CartesiaTTSOptions,
    GoogleTTSOptions,
    AmazonTTSOptions,
    HumeAITTSOptions,
    RimeTTSOptions,
    FishAudioTTSOptions,
    MiniMaxTTSOptions,
    MurfTTSOptions,
    SarvamTTSOptions,
    SpeechmaticsSTTOptions,
    DeepgramSTTOptions,
    MicrosoftSTTOptions,
    OpenAISTTOptions,
    GoogleSTTOptions,
    AmazonSTTOptions,
    AssemblyAISTTOptions,
    AresSTTOptions,
    SarvamSTTOptions,
    OpenAIRealtimeOptions,
    GeminiLiveOptions,
    VertexAIOptions,
    HeyGenAvatarOptions,
    LiveAvatarAvatarOptions,
    AkoolAvatarOptions,
    AnamAvatarOptions,
} from "./agentkit/index.js";
